/*
    This file is part of the WebKit open source project.
    This file has been generated by generate-bindings.pl. DO NOT MODIFY!

    This library is free software; you can redistribute it and/or
    modify it under the terms of the GNU Library General Public
    License as published by the Free Software Foundation; either
    version 2 of the License, or (at your option) any later version.

    This library is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
    Library General Public License for more details.

    You should have received a copy of the GNU Library General Public License
    along with this library; see the file COPYING.LIB.  If not, write to
    the Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor,
    Boston, MA 02110-1301, USA.
*/

#pragma once

#include "TestSerializable.h"
#include <WebCore/JSDOMWrapper.h>
#include <wtf/NeverDestroyed.h>

namespace WebCore {

class JSTestSerializable : public JSDOMWrapper<TestSerializable> {
public:
    using Base = JSDOMWrapper<TestSerializable>;
    static JSTestSerializable* create(JSC::Structure*, JSDOMGlobalObject*, Ref<TestSerializable>&&);

    static JSC::JSObject* createPrototype(JSC::VM&, JSDOMGlobalObject&);
    static JSC::JSObject* prototype(JSC::VM&, JSDOMGlobalObject&);
    static TestSerializable* toWrapped(JSC::VM&, JSC::JSValue);
    static void destroy(JSC::JSCell*);

    DECLARE_INFO;

    static JSC::Structure* createStructure(JSC::VM&, JSC::JSGlobalObject*, JSC::JSValue);
    static bool isExposedInGlobalObject(JSDOMGlobalObject&);
    template<typename, JSC::SubspaceAccess mode> static JSC::GCClient::IsoSubspace* subspaceFor(JSC::VM& vm)
    {
        if constexpr (mode == JSC::SubspaceAccess::Concurrently)
            return nullptr;
        return subspaceForImpl(vm);
    }
    static JSC::GCClient::IsoSubspace* subspaceForImpl(JSC::VM& vm);
    static void analyzeHeap(JSCell*, JSC::HeapAnalyzer&);
protected:
    JSTestSerializable(JSC::Structure*, JSDOMGlobalObject&, Ref<TestSerializable>&&);

    DECLARE_DEFAULT_FINISH_CREATION;
};

class JSTestSerializableOwner final : public JSC::WeakHandleOwner {
public:
    JSTestSerializableOwner() = default;
    bool isReachableFromOpaqueRoots(JSC::Handle<JSC::Unknown>, void* context, JSC::AbstractSlotVisitor&, ASCIILiteral*) final;
    void finalize(JSC::Handle<JSC::Unknown>, void* context) final;

private:
    explicit JSTestSerializableOwner(ClangVTableWorkaroundTag);
};

inline JSC::WeakHandleOwner* wrapperOwner(DOMWrapperWorld&, TestSerializable*)
{
    static NeverDestroyed<JSTestSerializableOwner> owner;
    return &owner.get();
}

inline void* wrapperKey(TestSerializable* wrappableObject)
{
    return wrappableObject;
}

JSC::JSValue toJS(JSC::JSGlobalObject*, JSDOMGlobalObject*, TestSerializable&);
JSC::JSValue toJSNewlyCreated(JSC::JSGlobalObject*, JSDOMGlobalObject*, Ref<TestSerializable>&&);
ALWAYS_INLINE JSC::JSValue toJSNewlyCreated(JSC::JSGlobalObject* lexicalGlobalObject, JSDOMGlobalObject* globalObject, TestSerializable& impl) { return toJSNewlyCreated(lexicalGlobalObject, globalObject, Ref { impl }); }

template<> struct JSDOMWrapperConverterTraits<TestSerializable> {
    using WrapperClass = JSTestSerializable;
    using ToWrappedReturnType = TestSerializable*;
};

} // namespace WebCore
