/*
    This file is part of the WebKit open source project.
    This file has been generated by generate-bindings.pl. DO NOT MODIFY!

    This library is free software; you can redistribute it and/or
    modify it under the terms of the GNU Library General Public
    License as published by the Free Software Foundation; either
    version 2 of the License, or (at your option) any later version.

    This library is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
    Library General Public License for more details.

    You should have received a copy of the GNU Library General Public License
    along with this library; see the file COPYING.LIB.  If not, write to
    the Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor,
    Boston, MA 02110-1301, USA.
*/

#include "config.h"
#include "JSTestSerializable.h"

#include "ActiveDOMObject.h"
#include "ContextDestructionObserverInlines.h"
#include "ExtendedDOMClientIsoSubspaces.h"
#include "ExtendedDOMIsoSubspaces.h"
#include "JSDOMBinding.h"
#include "JSDOMBindingFacade.h"
#include "JSDOMExceptionHandling.h"
#include "JSDOMWindowBase.h"
#include "JSDOMWrapperCache.h"
#include "JSDedicatedWorkerGlobalScope.h"
#include "JSTestSerializable.h"
#include "ScriptExecutionContext.h"
#include "Settings.h"
#include "WebCoreJSClientData.h"
#include <JavaScriptCore/HeapAnalyzer.h>
#include <JavaScriptCore/JSDestructibleObjectHeapCellType.h>
#include <JavaScriptCore/SlotVisitorMacros.h>
#include <JavaScriptCore/SubspaceInlines.h>
#include <wtf/GetPtr.h>
#include <wtf/PointerPreparations.h>
#include <wtf/URL.h>
#include <wtf/text/MakeString.h>

namespace WebCore {
using namespace JSC;

class JSTestSerializablePrototype final : public JSC::JSNonFinalObject {
public:
    using Base = JSC::JSNonFinalObject;
    static JSTestSerializablePrototype* create(JSC::VM& vm, JSDOMGlobalObject* globalObject, JSC::Structure* structure)
    {
        JSTestSerializablePrototype* ptr = new (NotNull, JSC::allocateCell<JSTestSerializablePrototype>(vm)) JSTestSerializablePrototype(vm, globalObject, structure);
        ptr->finishCreation(vm);
        return ptr;
    }

    DECLARE_INFO;
    template<typename CellType, JSC::SubspaceAccess>
    static JSC::GCClient::IsoSubspace* subspaceFor(JSC::VM& vm)
    {
        STATIC_ASSERT_ISO_SUBSPACE_SHARABLE(JSTestSerializablePrototype, Base);
        return &vm.plainObjectSpace();
    }
    static JSC::Structure* createStructure(JSC::VM&, JSC::JSGlobalObject*, JSC::JSValue);

private:
    JSTestSerializablePrototype(JSC::VM& vm, JSC::JSGlobalObject*, JSC::Structure* structure)
        : JSC::JSNonFinalObject(vm, structure)
    {
    }

    void finishCreation(JSC::VM&);
};
STATIC_ASSERT_ISO_SUBSPACE_SHARABLE(JSTestSerializablePrototype, JSTestSerializablePrototype::Base);

/* Hash table for prototype */
const ClassInfo JSTestSerializablePrototype::s_info = { "TestSerializable"_s, &Base::s_info, nullptr, nullptr, CREATE_METHOD_TABLE(JSTestSerializablePrototype) };

JSC::Structure* JSTestSerializablePrototype::createStructure(JSC::VM& vm, JSC::JSGlobalObject* globalObject, JSC::JSValue prototype)
{
    return JSC::Structure::create(vm, globalObject, prototype, JSC::TypeInfo(JSC::ObjectType, StructureFlags), info(), JSC::NonArray);
}

void JSTestSerializablePrototype::finishCreation(VM& vm)
{
    Base::finishCreation(vm);
    WebCore::putDirectWithoutTransition(this, vm, vm.propertyNames->toStringTagSymbol, jsNontrivialString(vm, info()->className), JSC::PropertyAttribute::DontEnum | JSC::PropertyAttribute::ReadOnly);
}

const ClassInfo JSTestSerializable::s_info = { "TestSerializable"_s, &Base::s_info, nullptr, nullptr, CREATE_METHOD_TABLE(JSTestSerializable) };

JSTestSerializable::JSTestSerializable(Structure* structure, JSDOMGlobalObject& globalObject, Ref<TestSerializable>&& impl)
    : JSDOMWrapper<TestSerializable>(structure, globalObject, WTF::move(impl))
{
}

static_assert(!std::is_base_of<ActiveDOMObject, TestSerializable>::value, "Interface is not marked as [ActiveDOMObject] even though implementation class subclasses ActiveDOMObject.");

JSTestSerializable* JSTestSerializable::create(JSC::Structure* structure, JSDOMGlobalObject* globalObject, Ref<TestSerializable>&& impl)
{
    auto& vm = globalObject->vm();
    JSTestSerializable* ptr = new (NotNull, JSC::allocateCell<JSTestSerializable>(vm)) JSTestSerializable(structure, *globalObject, WTF::move(impl));
    ptr->finishCreation(vm);
    return ptr;
}

JSC::Structure* JSTestSerializable::createStructure(JSC::VM& vm, JSC::JSGlobalObject* globalObject, JSC::JSValue prototype)
{
    return JSC::Structure::create(vm, globalObject, prototype, JSC::TypeInfo(JSC::ObjectType, StructureFlags), info(), JSC::NonArray);
}

JSObject* JSTestSerializable::createPrototype(VM& vm, JSDOMGlobalObject& globalObject)
{
    auto* structure = JSTestSerializablePrototype::createStructure(vm, &globalObject, globalObject.objectPrototype());
    structure->setMayBePrototype(true);
    return JSTestSerializablePrototype::create(vm, &globalObject, structure);
}

JSObject* JSTestSerializable::prototype(VM& vm, JSDOMGlobalObject& globalObject)
{
    return getDOMPrototype<JSTestSerializable>(vm, globalObject);
}

bool JSTestSerializable::isExposedInGlobalObject(JSDOMGlobalObject& globalObject)
{
    return ((&globalObject)->scriptExecutionContext()->isSecureContext() && (((&globalObject))->inherits<JSDOMWindowBase>() || ((&globalObject))->inherits<JSDedicatedWorkerGlobalScope>()) && (&globalObject)->scriptExecutionContext()->settingsValues().testSettingEnabled && TestSerializable::enabledForContext(*protect((&globalObject)->scriptExecutionContext())));
}

void JSTestSerializable::destroy(JSC::JSCell* cell)
{
    SUPPRESS_MEMORY_UNSAFE_CAST JSTestSerializable* thisObject = static_cast<JSTestSerializable*>(cell);
    thisObject->JSTestSerializable::~JSTestSerializable();
}

JSC::GCClient::IsoSubspace* JSTestSerializable::subspaceForImpl(JSC::VM& vm)
{
    return WebCore::subspaceForImpl<JSTestSerializable, UseCustomHeapCellType::No>(vm, "JSTestSerializable"_s,
        [] (auto& spaces) { return spaces.m_clientSubspaceForTestSerializable.get(); },
        [] (auto& spaces, auto&& space) { spaces.m_clientSubspaceForTestSerializable = std::forward<decltype(space)>(space); },
        [] (auto& spaces) { return spaces.m_subspaceForTestSerializable.get(); },
        [] (auto& spaces, auto&& space) { spaces.m_subspaceForTestSerializable = std::forward<decltype(space)>(space); }
    );
}

void JSTestSerializable::analyzeHeap(JSCell* cell, HeapAnalyzer& analyzer)
{
    auto* thisObject = uncheckedDowncast<JSTestSerializable>(cell);
    analyzer.setWrappedObjectForCell(cell, &thisObject->wrapped());
    if (RefPtr context = thisObject->scriptExecutionContext())
        analyzer.setLabelForCell(cell, makeString("url "_s, context->url().string()));
    Base::analyzeHeap(cell, analyzer);
}

JSTestSerializableOwner::JSTestSerializableOwner(ClangVTableWorkaroundTag) { }

bool JSTestSerializableOwner::isReachableFromOpaqueRoots(JSC::Handle<JSC::Unknown> handle, void*, AbstractSlotVisitor& visitor, ASCIILiteral* reason)
{
    UNUSED_PARAM(handle);
    UNUSED_PARAM(visitor);
    UNUSED_PARAM(reason);
    return false;
}

void JSTestSerializableOwner::finalize(JSC::Handle<JSC::Unknown> handle, void* context)
{
    SUPPRESS_MEMORY_UNSAFE_CAST auto* jsTestSerializable = static_cast<JSTestSerializable*>(handle.slot()->asCell());
    auto& world = *static_cast<DOMWrapperWorld*>(context);
    SUPPRESS_UNCOUNTED_ARG uncacheWrapper(world, &jsTestSerializable->wrapped(), jsTestSerializable);
}

WTF_ALLOW_UNSAFE_BUFFER_USAGE_BEGIN
#if ENABLE(BINDING_INTEGRITY)
#if PLATFORM(WIN)
#pragma warning(disable: 4483)
extern "C" { extern void (*const __identifier("??_7TestSerializable@WebCore@@6B@")[])(); }
#else
extern "C" { extern void* _ZTVN7WebCore16TestSerializableE[]; }
#endif
template<std::same_as<TestSerializable> T>
static inline void verifyVTable(TestSerializable* ptr)
{
    if constexpr (std::is_polymorphic_v<T>) {
        const void* actualVTablePointer = getVTablePointer<T>(ptr);
#if PLATFORM(WIN)
        void* expectedVTablePointer = __identifier("??_7TestSerializable@WebCore@@6B@");
#else
        void* expectedVTablePointer = &_ZTVN7WebCore16TestSerializableE[2];
#endif

        // If you hit this assertion you either have a use after free bug, or
        // TestSerializable has subclasses. If TestSerializable has subclasses that get passed
        // to toJS() we currently require TestSerializable you to opt out of binding hardening
        // by adding the SkipVTableValidation attribute to the interface IDL definition
        RELEASE_ASSERT_WITH_UNQUALIFIED_FUNCTION_NAME(actualVTablePointer == expectedVTablePointer);
    }
}
#endif
WTF_ALLOW_UNSAFE_BUFFER_USAGE_END

JSC::JSValue toJSNewlyCreated(JSC::JSGlobalObject* lexicalGlobalObject, JSDOMGlobalObject* globalObject, Ref<TestSerializable>&& impl)
{
    UNUSED_PARAM(lexicalGlobalObject);
#if ENABLE(BINDING_INTEGRITY)
    verifyVTable<TestSerializable>(impl.ptr());
#endif
    return createWrapper<TestSerializable>(globalObject, WTF::move(impl));
}

JSC::JSValue toJS(JSC::JSGlobalObject* lexicalGlobalObject, JSDOMGlobalObject* globalObject, TestSerializable& impl)
{
    return wrap(lexicalGlobalObject, globalObject, impl);
}

TestSerializable* JSTestSerializable::toWrapped(JSC::VM&, JSC::JSValue value)
{
    if (auto* wrapper = dynamicDowncast<JSTestSerializable>(value))
        return &wrapper->wrapped();
    return nullptr;
}

}
