// This file is automatically generated from CSSProperties.json by the process-css-properties.py script. Do not edit it.

#pragma once

#include <array>
#include <wtf/HashFunctions.h>
#include <wtf/HashTraits.h>

namespace WebCore {

class Settings;

enum class CSSPropertyID : uint16_t {
    Invalid = 0,
    Custom = 1,
    TestTopPriority = 2,
    TestHighPriority = 3,
    TestMediumPriority = 4,
    BackgroundCoordinatedValueListPropertyTestDiscrete = 5,
    BackgroundCoordinatedValueListPropertyTestTwo = 6,
    FirstTestDescriptorForFirstDescriptor = 7,
    FirstTestDescriptorForSecondDescriptor = 8,
    TestAnimationWrapper = 9,
    TestAnimationWrapperAccelerationAlways = 10,
    TestAnimationWrapperAccelerationThreadedOnly = 11,
    TestBoundedRepetitionWithCommas = 12,
    TestBoundedRepetitionWithCommasFixed = 13,
    TestBoundedRepetitionWithCommasNoSingleItemOpt = 14,
    TestBoundedRepetitionWithCommasSingleItemOpt = 15,
    TestBoundedRepetitionWithSpaces = 16,
    TestBoundedRepetitionWithSpacesFixed = 17,
    TestBoundedRepetitionWithSpacesNoSingleItemOpt = 18,
    TestBoundedRepetitionWithSpacesSingleItemOpt = 19,
    TestBoundedRepetitionWithSpacesWithType = 20,
    TestBoundedRepetitionWithSpacesWithTypeNoSingleItemOpt = 21,
    TestBoundedRepetitionWithSpacesWithTypeWithDefaultPrevious = 22,
    TestBoundedRepetitionWithSpacesWithTypeWithDefaultPreviousTwo = 23,
    TestColor = 24,
    TestColorAllowsTypesAbsolute = 25,
    TestColorPropertyWithVisitedLinkSupport = 26,
    TestCustomExtractor = 27,
    TestFunctionBoundedParameters = 28,
    TestFunctionFixedParameters = 29,
    TestFunctionNoParameters = 30,
    TestFunctionParametersMatchAllAnyOrder = 31,
    TestFunctionParametersMatchAllAnyOrderWithOptional = 32,
    TestFunctionParametersMatchAllOrdered = 33,
    TestFunctionParametersMatchAllOrderedWithOptional = 34,
    TestFunctionParametersMatchOneOrMoreAnyOrder = 35,
    TestFunctionSingleParameter = 36,
    TestFunctionSingleParameterMatchOne = 37,
    TestFunctionSingleParameterOptional = 38,
    TestFunctionUnboundedParametersNoMin = 39,
    TestFunctionUnboundedParametersWithMinimum = 40,
    TestImage = 41,
    TestImageNoImageSet = 42,
    TestKeyword = 43,
    TestKeywordWithAliasedTo = 44,
    TestMatchAllAnyOrder = 45,
    TestMatchAllAnyOrderWithCustomType = 46,
    TestMatchAllAnyOrderWithOptional = 47,
    TestMatchAllAnyOrderWithOptionalAndCustomType = 48,
    TestMatchAllAnyOrderWithOptionalAndMultipleRequiredAndCustomType = 49,
    TestMatchAllAnyOrderWithOptionalAndMultipleRequiredAndCustomTypeNoSingleItemOpt = 50,
    TestMatchAllAnyOrderWithOptionalAndMultipleRequiredAndPreserveOrderAndCustomType = 51,
    TestMatchAllAnyOrderWithOptionalAndMultipleRequiredAndPreserveOrderAndCustomTypeNoSingleItemOpt = 52,
    TestMatchAllAnyOrderWithOptionalAndPreserveOrderAndCustomType = 53,
    TestMatchAllAnyOrderWithOptionalNoSingleItemOpt = 54,
    TestMatchAllAnyOrderWithOptionalSingleItemOpt = 55,
    TestMatchAllAnyOrderWithOptionalWithPreserveOrder = 56,
    TestMatchAllAnyOrderWithOptionalWithPreserveOrderNoSingleItemOpt = 57,
    TestMatchAllAnyOrderWithPreserveOrder = 58,
    TestMatchAllAnyOrderWithPreserveOrderAndCustomType = 59,
    TestMatchAllAnyOrderWithPreserveOrderNoSingleItemOpt = 60,
    TestMatchAllOrdered = 61,
    TestMatchAllOrderedWithCustomType = 62,
    TestMatchAllOrderedWithOptional = 63,
    TestMatchAllOrderedWithOptionalAndCustomType = 64,
    TestMatchAllOrderedWithOptionalAndCustomTypeAndNoSingleItemOpt = 65,
    TestMatchAllOrderedWithOptionalAndMultipleRequired = 66,
    TestMatchAllOrderedWithOptionalAndMultipleRequiredAndCustomType = 67,
    TestMatchAllOrderedWithOptionalNoSingleItemOpt = 68,
    TestMatchAllOrderedWithOptionalSingleItemOpt = 69,
    TestMatchOne = 70,
    TestMatchOneOrMoreAnyOrder = 71,
    TestMatchOneOrMoreAnyOrderNoSingleItemOpt = 72,
    TestMatchOneOrMoreAnyOrderWithCustomType = 73,
    TestMatchOneOrMoreAnyOrderWithCustomTypeNoSingleItemOpt = 74,
    TestMatchOneOrMoreAnyOrderWithPreserveOrder = 75,
    TestMatchOneOrMoreAnyOrderWithPreserveOrderAndCustomType = 76,
    TestMatchOneOrMoreAnyOrderWithPreserveOrderAndCustomTypeNoSingleItemOpt = 77,
    TestMatchOneOrMoreAnyOrderWithPreserveOrderNoSingleItemOpt = 78,
    TestMatchOneWithGroupWithSettingsFlag = 79,
    TestMatchOneWithKeywordWithSettingsFlag = 80,
    TestMatchOneWithMultipleKeywords = 81,
    TestMatchOneWithReferenceWithSettingsFlag = 82,
    TestMatchOneWithSettingsFlag = 83,
    TestNumericValueRange = 84,
    TestProperty = 85,
    TestRenderStyleGetterNodeleteFalse = 86,
    TestRenderStyleHasExplicitlySetPolicyAllAuthorOrigin = 87,
    TestRenderStyleHasExplicitlySetPolicyAllBorderRadius = 88,
    TestRenderStyleHasExplicitlySetPolicyValueOnly = 89,
    TestRenderStyleStorageOneLevelEnum = 90,
    TestRenderStyleStorageOneLevelRaw = 91,
    TestRenderStyleStorageOneLevelReference = 92,
    TestRenderStyleStorageOneLevelValue = 93,
    TestRenderStyleStorageTwoLevelEnum = 94,
    TestRenderStyleStorageTwoLevelRaw = 95,
    TestRenderStyleStorageTwoLevelReference = 96,
    TestRenderStyleStorageTwoLevelValue = 97,
    TestSettingsOne = 98,
    TestUnboundedRepetitionWithCommasWithMin = 99,
    TestUnboundedRepetitionWithCommasWithMinNoSingleItemOpt = 100,
    TestUnboundedRepetitionWithCommasWithMinSingleItemOpt = 101,
    TestUnboundedRepetitionWithSpacesNoMin = 102,
    TestUnboundedRepetitionWithSpacesNoMinNoSingleItemOpt = 103,
    TestUnboundedRepetitionWithSpacesWithMin = 104,
    TestUnboundedRepetitionWithSpacesWithMinNoSingleItemOpt = 105,
    TestUnboundedRepetitionWithSpacesWithMinSingleItemOpt = 106,
    TestUrlWithModifiers = 107,
    TestUrlWithNoModifiers = 108,
    TestUsingSharedRule = 109,
    TestUsingSharedRuleExported = 110,
    TestUsingSharedRuleWithOverrideFunction = 111,
    TestSinkPriority = 112,
    TestLogicalPropertyGroupPhysicalHorizontal = 113,
    TestLogicalPropertyGroupPhysicalVertical = 114,
    TestLogicalPropertyGroupLogicalBlock = 115,
    TestLogicalPropertyGroupLogicalInline = 116,
    All = 117,
    Font = 118,
    TestShorthandOne = 119,
    TestShorthandTwo = 120,
};

// FIXME: Remove these once all call sites use CSSPropertyID::Foo.
inline constexpr CSSPropertyID CSSPropertyInvalid = CSSPropertyID::Invalid;
inline constexpr CSSPropertyID CSSPropertyCustom = CSSPropertyID::Custom;
inline constexpr CSSPropertyID CSSPropertyTestTopPriority = CSSPropertyID::TestTopPriority;
inline constexpr CSSPropertyID CSSPropertyTestHighPriority = CSSPropertyID::TestHighPriority;
inline constexpr CSSPropertyID CSSPropertyTestMediumPriority = CSSPropertyID::TestMediumPriority;
inline constexpr CSSPropertyID CSSPropertyBackgroundCoordinatedValueListPropertyTestDiscrete = CSSPropertyID::BackgroundCoordinatedValueListPropertyTestDiscrete;
inline constexpr CSSPropertyID CSSPropertyBackgroundCoordinatedValueListPropertyTestTwo = CSSPropertyID::BackgroundCoordinatedValueListPropertyTestTwo;
inline constexpr CSSPropertyID CSSPropertyFirstTestDescriptorForFirstDescriptor = CSSPropertyID::FirstTestDescriptorForFirstDescriptor;
inline constexpr CSSPropertyID CSSPropertyFirstTestDescriptorForSecondDescriptor = CSSPropertyID::FirstTestDescriptorForSecondDescriptor;
inline constexpr CSSPropertyID CSSPropertyTestAnimationWrapper = CSSPropertyID::TestAnimationWrapper;
inline constexpr CSSPropertyID CSSPropertyTestAnimationWrapperAccelerationAlways = CSSPropertyID::TestAnimationWrapperAccelerationAlways;
inline constexpr CSSPropertyID CSSPropertyTestAnimationWrapperAccelerationThreadedOnly = CSSPropertyID::TestAnimationWrapperAccelerationThreadedOnly;
inline constexpr CSSPropertyID CSSPropertyTestBoundedRepetitionWithCommas = CSSPropertyID::TestBoundedRepetitionWithCommas;
inline constexpr CSSPropertyID CSSPropertyTestBoundedRepetitionWithCommasFixed = CSSPropertyID::TestBoundedRepetitionWithCommasFixed;
inline constexpr CSSPropertyID CSSPropertyTestBoundedRepetitionWithCommasNoSingleItemOpt = CSSPropertyID::TestBoundedRepetitionWithCommasNoSingleItemOpt;
inline constexpr CSSPropertyID CSSPropertyTestBoundedRepetitionWithCommasSingleItemOpt = CSSPropertyID::TestBoundedRepetitionWithCommasSingleItemOpt;
inline constexpr CSSPropertyID CSSPropertyTestBoundedRepetitionWithSpaces = CSSPropertyID::TestBoundedRepetitionWithSpaces;
inline constexpr CSSPropertyID CSSPropertyTestBoundedRepetitionWithSpacesFixed = CSSPropertyID::TestBoundedRepetitionWithSpacesFixed;
inline constexpr CSSPropertyID CSSPropertyTestBoundedRepetitionWithSpacesNoSingleItemOpt = CSSPropertyID::TestBoundedRepetitionWithSpacesNoSingleItemOpt;
inline constexpr CSSPropertyID CSSPropertyTestBoundedRepetitionWithSpacesSingleItemOpt = CSSPropertyID::TestBoundedRepetitionWithSpacesSingleItemOpt;
inline constexpr CSSPropertyID CSSPropertyTestBoundedRepetitionWithSpacesWithType = CSSPropertyID::TestBoundedRepetitionWithSpacesWithType;
inline constexpr CSSPropertyID CSSPropertyTestBoundedRepetitionWithSpacesWithTypeNoSingleItemOpt = CSSPropertyID::TestBoundedRepetitionWithSpacesWithTypeNoSingleItemOpt;
inline constexpr CSSPropertyID CSSPropertyTestBoundedRepetitionWithSpacesWithTypeWithDefaultPrevious = CSSPropertyID::TestBoundedRepetitionWithSpacesWithTypeWithDefaultPrevious;
inline constexpr CSSPropertyID CSSPropertyTestBoundedRepetitionWithSpacesWithTypeWithDefaultPreviousTwo = CSSPropertyID::TestBoundedRepetitionWithSpacesWithTypeWithDefaultPreviousTwo;
inline constexpr CSSPropertyID CSSPropertyTestColor = CSSPropertyID::TestColor;
inline constexpr CSSPropertyID CSSPropertyTestColorAllowsTypesAbsolute = CSSPropertyID::TestColorAllowsTypesAbsolute;
inline constexpr CSSPropertyID CSSPropertyTestColorPropertyWithVisitedLinkSupport = CSSPropertyID::TestColorPropertyWithVisitedLinkSupport;
inline constexpr CSSPropertyID CSSPropertyTestCustomExtractor = CSSPropertyID::TestCustomExtractor;
inline constexpr CSSPropertyID CSSPropertyTestFunctionBoundedParameters = CSSPropertyID::TestFunctionBoundedParameters;
inline constexpr CSSPropertyID CSSPropertyTestFunctionFixedParameters = CSSPropertyID::TestFunctionFixedParameters;
inline constexpr CSSPropertyID CSSPropertyTestFunctionNoParameters = CSSPropertyID::TestFunctionNoParameters;
inline constexpr CSSPropertyID CSSPropertyTestFunctionParametersMatchAllAnyOrder = CSSPropertyID::TestFunctionParametersMatchAllAnyOrder;
inline constexpr CSSPropertyID CSSPropertyTestFunctionParametersMatchAllAnyOrderWithOptional = CSSPropertyID::TestFunctionParametersMatchAllAnyOrderWithOptional;
inline constexpr CSSPropertyID CSSPropertyTestFunctionParametersMatchAllOrdered = CSSPropertyID::TestFunctionParametersMatchAllOrdered;
inline constexpr CSSPropertyID CSSPropertyTestFunctionParametersMatchAllOrderedWithOptional = CSSPropertyID::TestFunctionParametersMatchAllOrderedWithOptional;
inline constexpr CSSPropertyID CSSPropertyTestFunctionParametersMatchOneOrMoreAnyOrder = CSSPropertyID::TestFunctionParametersMatchOneOrMoreAnyOrder;
inline constexpr CSSPropertyID CSSPropertyTestFunctionSingleParameter = CSSPropertyID::TestFunctionSingleParameter;
inline constexpr CSSPropertyID CSSPropertyTestFunctionSingleParameterMatchOne = CSSPropertyID::TestFunctionSingleParameterMatchOne;
inline constexpr CSSPropertyID CSSPropertyTestFunctionSingleParameterOptional = CSSPropertyID::TestFunctionSingleParameterOptional;
inline constexpr CSSPropertyID CSSPropertyTestFunctionUnboundedParametersNoMin = CSSPropertyID::TestFunctionUnboundedParametersNoMin;
inline constexpr CSSPropertyID CSSPropertyTestFunctionUnboundedParametersWithMinimum = CSSPropertyID::TestFunctionUnboundedParametersWithMinimum;
inline constexpr CSSPropertyID CSSPropertyTestImage = CSSPropertyID::TestImage;
inline constexpr CSSPropertyID CSSPropertyTestImageNoImageSet = CSSPropertyID::TestImageNoImageSet;
inline constexpr CSSPropertyID CSSPropertyTestKeyword = CSSPropertyID::TestKeyword;
inline constexpr CSSPropertyID CSSPropertyTestKeywordWithAliasedTo = CSSPropertyID::TestKeywordWithAliasedTo;
inline constexpr CSSPropertyID CSSPropertyTestMatchAllAnyOrder = CSSPropertyID::TestMatchAllAnyOrder;
inline constexpr CSSPropertyID CSSPropertyTestMatchAllAnyOrderWithCustomType = CSSPropertyID::TestMatchAllAnyOrderWithCustomType;
inline constexpr CSSPropertyID CSSPropertyTestMatchAllAnyOrderWithOptional = CSSPropertyID::TestMatchAllAnyOrderWithOptional;
inline constexpr CSSPropertyID CSSPropertyTestMatchAllAnyOrderWithOptionalAndCustomType = CSSPropertyID::TestMatchAllAnyOrderWithOptionalAndCustomType;
inline constexpr CSSPropertyID CSSPropertyTestMatchAllAnyOrderWithOptionalAndMultipleRequiredAndCustomType = CSSPropertyID::TestMatchAllAnyOrderWithOptionalAndMultipleRequiredAndCustomType;
inline constexpr CSSPropertyID CSSPropertyTestMatchAllAnyOrderWithOptionalAndMultipleRequiredAndCustomTypeNoSingleItemOpt = CSSPropertyID::TestMatchAllAnyOrderWithOptionalAndMultipleRequiredAndCustomTypeNoSingleItemOpt;
inline constexpr CSSPropertyID CSSPropertyTestMatchAllAnyOrderWithOptionalAndMultipleRequiredAndPreserveOrderAndCustomType = CSSPropertyID::TestMatchAllAnyOrderWithOptionalAndMultipleRequiredAndPreserveOrderAndCustomType;
inline constexpr CSSPropertyID CSSPropertyTestMatchAllAnyOrderWithOptionalAndMultipleRequiredAndPreserveOrderAndCustomTypeNoSingleItemOpt = CSSPropertyID::TestMatchAllAnyOrderWithOptionalAndMultipleRequiredAndPreserveOrderAndCustomTypeNoSingleItemOpt;
inline constexpr CSSPropertyID CSSPropertyTestMatchAllAnyOrderWithOptionalAndPreserveOrderAndCustomType = CSSPropertyID::TestMatchAllAnyOrderWithOptionalAndPreserveOrderAndCustomType;
inline constexpr CSSPropertyID CSSPropertyTestMatchAllAnyOrderWithOptionalNoSingleItemOpt = CSSPropertyID::TestMatchAllAnyOrderWithOptionalNoSingleItemOpt;
inline constexpr CSSPropertyID CSSPropertyTestMatchAllAnyOrderWithOptionalSingleItemOpt = CSSPropertyID::TestMatchAllAnyOrderWithOptionalSingleItemOpt;
inline constexpr CSSPropertyID CSSPropertyTestMatchAllAnyOrderWithOptionalWithPreserveOrder = CSSPropertyID::TestMatchAllAnyOrderWithOptionalWithPreserveOrder;
inline constexpr CSSPropertyID CSSPropertyTestMatchAllAnyOrderWithOptionalWithPreserveOrderNoSingleItemOpt = CSSPropertyID::TestMatchAllAnyOrderWithOptionalWithPreserveOrderNoSingleItemOpt;
inline constexpr CSSPropertyID CSSPropertyTestMatchAllAnyOrderWithPreserveOrder = CSSPropertyID::TestMatchAllAnyOrderWithPreserveOrder;
inline constexpr CSSPropertyID CSSPropertyTestMatchAllAnyOrderWithPreserveOrderAndCustomType = CSSPropertyID::TestMatchAllAnyOrderWithPreserveOrderAndCustomType;
inline constexpr CSSPropertyID CSSPropertyTestMatchAllAnyOrderWithPreserveOrderNoSingleItemOpt = CSSPropertyID::TestMatchAllAnyOrderWithPreserveOrderNoSingleItemOpt;
inline constexpr CSSPropertyID CSSPropertyTestMatchAllOrdered = CSSPropertyID::TestMatchAllOrdered;
inline constexpr CSSPropertyID CSSPropertyTestMatchAllOrderedWithCustomType = CSSPropertyID::TestMatchAllOrderedWithCustomType;
inline constexpr CSSPropertyID CSSPropertyTestMatchAllOrderedWithOptional = CSSPropertyID::TestMatchAllOrderedWithOptional;
inline constexpr CSSPropertyID CSSPropertyTestMatchAllOrderedWithOptionalAndCustomType = CSSPropertyID::TestMatchAllOrderedWithOptionalAndCustomType;
inline constexpr CSSPropertyID CSSPropertyTestMatchAllOrderedWithOptionalAndCustomTypeAndNoSingleItemOpt = CSSPropertyID::TestMatchAllOrderedWithOptionalAndCustomTypeAndNoSingleItemOpt;
inline constexpr CSSPropertyID CSSPropertyTestMatchAllOrderedWithOptionalAndMultipleRequired = CSSPropertyID::TestMatchAllOrderedWithOptionalAndMultipleRequired;
inline constexpr CSSPropertyID CSSPropertyTestMatchAllOrderedWithOptionalAndMultipleRequiredAndCustomType = CSSPropertyID::TestMatchAllOrderedWithOptionalAndMultipleRequiredAndCustomType;
inline constexpr CSSPropertyID CSSPropertyTestMatchAllOrderedWithOptionalNoSingleItemOpt = CSSPropertyID::TestMatchAllOrderedWithOptionalNoSingleItemOpt;
inline constexpr CSSPropertyID CSSPropertyTestMatchAllOrderedWithOptionalSingleItemOpt = CSSPropertyID::TestMatchAllOrderedWithOptionalSingleItemOpt;
inline constexpr CSSPropertyID CSSPropertyTestMatchOne = CSSPropertyID::TestMatchOne;
inline constexpr CSSPropertyID CSSPropertyTestMatchOneOrMoreAnyOrder = CSSPropertyID::TestMatchOneOrMoreAnyOrder;
inline constexpr CSSPropertyID CSSPropertyTestMatchOneOrMoreAnyOrderNoSingleItemOpt = CSSPropertyID::TestMatchOneOrMoreAnyOrderNoSingleItemOpt;
inline constexpr CSSPropertyID CSSPropertyTestMatchOneOrMoreAnyOrderWithCustomType = CSSPropertyID::TestMatchOneOrMoreAnyOrderWithCustomType;
inline constexpr CSSPropertyID CSSPropertyTestMatchOneOrMoreAnyOrderWithCustomTypeNoSingleItemOpt = CSSPropertyID::TestMatchOneOrMoreAnyOrderWithCustomTypeNoSingleItemOpt;
inline constexpr CSSPropertyID CSSPropertyTestMatchOneOrMoreAnyOrderWithPreserveOrder = CSSPropertyID::TestMatchOneOrMoreAnyOrderWithPreserveOrder;
inline constexpr CSSPropertyID CSSPropertyTestMatchOneOrMoreAnyOrderWithPreserveOrderAndCustomType = CSSPropertyID::TestMatchOneOrMoreAnyOrderWithPreserveOrderAndCustomType;
inline constexpr CSSPropertyID CSSPropertyTestMatchOneOrMoreAnyOrderWithPreserveOrderAndCustomTypeNoSingleItemOpt = CSSPropertyID::TestMatchOneOrMoreAnyOrderWithPreserveOrderAndCustomTypeNoSingleItemOpt;
inline constexpr CSSPropertyID CSSPropertyTestMatchOneOrMoreAnyOrderWithPreserveOrderNoSingleItemOpt = CSSPropertyID::TestMatchOneOrMoreAnyOrderWithPreserveOrderNoSingleItemOpt;
inline constexpr CSSPropertyID CSSPropertyTestMatchOneWithGroupWithSettingsFlag = CSSPropertyID::TestMatchOneWithGroupWithSettingsFlag;
inline constexpr CSSPropertyID CSSPropertyTestMatchOneWithKeywordWithSettingsFlag = CSSPropertyID::TestMatchOneWithKeywordWithSettingsFlag;
inline constexpr CSSPropertyID CSSPropertyTestMatchOneWithMultipleKeywords = CSSPropertyID::TestMatchOneWithMultipleKeywords;
inline constexpr CSSPropertyID CSSPropertyTestMatchOneWithReferenceWithSettingsFlag = CSSPropertyID::TestMatchOneWithReferenceWithSettingsFlag;
inline constexpr CSSPropertyID CSSPropertyTestMatchOneWithSettingsFlag = CSSPropertyID::TestMatchOneWithSettingsFlag;
inline constexpr CSSPropertyID CSSPropertyTestNumericValueRange = CSSPropertyID::TestNumericValueRange;
inline constexpr CSSPropertyID CSSPropertyTestProperty = CSSPropertyID::TestProperty;
inline constexpr CSSPropertyID CSSPropertyTestRenderStyleGetterNodeleteFalse = CSSPropertyID::TestRenderStyleGetterNodeleteFalse;
inline constexpr CSSPropertyID CSSPropertyTestRenderStyleHasExplicitlySetPolicyAllAuthorOrigin = CSSPropertyID::TestRenderStyleHasExplicitlySetPolicyAllAuthorOrigin;
inline constexpr CSSPropertyID CSSPropertyTestRenderStyleHasExplicitlySetPolicyAllBorderRadius = CSSPropertyID::TestRenderStyleHasExplicitlySetPolicyAllBorderRadius;
inline constexpr CSSPropertyID CSSPropertyTestRenderStyleHasExplicitlySetPolicyValueOnly = CSSPropertyID::TestRenderStyleHasExplicitlySetPolicyValueOnly;
inline constexpr CSSPropertyID CSSPropertyTestRenderStyleStorageOneLevelEnum = CSSPropertyID::TestRenderStyleStorageOneLevelEnum;
inline constexpr CSSPropertyID CSSPropertyTestRenderStyleStorageOneLevelRaw = CSSPropertyID::TestRenderStyleStorageOneLevelRaw;
inline constexpr CSSPropertyID CSSPropertyTestRenderStyleStorageOneLevelReference = CSSPropertyID::TestRenderStyleStorageOneLevelReference;
inline constexpr CSSPropertyID CSSPropertyTestRenderStyleStorageOneLevelValue = CSSPropertyID::TestRenderStyleStorageOneLevelValue;
inline constexpr CSSPropertyID CSSPropertyTestRenderStyleStorageTwoLevelEnum = CSSPropertyID::TestRenderStyleStorageTwoLevelEnum;
inline constexpr CSSPropertyID CSSPropertyTestRenderStyleStorageTwoLevelRaw = CSSPropertyID::TestRenderStyleStorageTwoLevelRaw;
inline constexpr CSSPropertyID CSSPropertyTestRenderStyleStorageTwoLevelReference = CSSPropertyID::TestRenderStyleStorageTwoLevelReference;
inline constexpr CSSPropertyID CSSPropertyTestRenderStyleStorageTwoLevelValue = CSSPropertyID::TestRenderStyleStorageTwoLevelValue;
inline constexpr CSSPropertyID CSSPropertyTestSettingsOne = CSSPropertyID::TestSettingsOne;
inline constexpr CSSPropertyID CSSPropertyTestUnboundedRepetitionWithCommasWithMin = CSSPropertyID::TestUnboundedRepetitionWithCommasWithMin;
inline constexpr CSSPropertyID CSSPropertyTestUnboundedRepetitionWithCommasWithMinNoSingleItemOpt = CSSPropertyID::TestUnboundedRepetitionWithCommasWithMinNoSingleItemOpt;
inline constexpr CSSPropertyID CSSPropertyTestUnboundedRepetitionWithCommasWithMinSingleItemOpt = CSSPropertyID::TestUnboundedRepetitionWithCommasWithMinSingleItemOpt;
inline constexpr CSSPropertyID CSSPropertyTestUnboundedRepetitionWithSpacesNoMin = CSSPropertyID::TestUnboundedRepetitionWithSpacesNoMin;
inline constexpr CSSPropertyID CSSPropertyTestUnboundedRepetitionWithSpacesNoMinNoSingleItemOpt = CSSPropertyID::TestUnboundedRepetitionWithSpacesNoMinNoSingleItemOpt;
inline constexpr CSSPropertyID CSSPropertyTestUnboundedRepetitionWithSpacesWithMin = CSSPropertyID::TestUnboundedRepetitionWithSpacesWithMin;
inline constexpr CSSPropertyID CSSPropertyTestUnboundedRepetitionWithSpacesWithMinNoSingleItemOpt = CSSPropertyID::TestUnboundedRepetitionWithSpacesWithMinNoSingleItemOpt;
inline constexpr CSSPropertyID CSSPropertyTestUnboundedRepetitionWithSpacesWithMinSingleItemOpt = CSSPropertyID::TestUnboundedRepetitionWithSpacesWithMinSingleItemOpt;
inline constexpr CSSPropertyID CSSPropertyTestUrlWithModifiers = CSSPropertyID::TestUrlWithModifiers;
inline constexpr CSSPropertyID CSSPropertyTestUrlWithNoModifiers = CSSPropertyID::TestUrlWithNoModifiers;
inline constexpr CSSPropertyID CSSPropertyTestUsingSharedRule = CSSPropertyID::TestUsingSharedRule;
inline constexpr CSSPropertyID CSSPropertyTestUsingSharedRuleExported = CSSPropertyID::TestUsingSharedRuleExported;
inline constexpr CSSPropertyID CSSPropertyTestUsingSharedRuleWithOverrideFunction = CSSPropertyID::TestUsingSharedRuleWithOverrideFunction;
inline constexpr CSSPropertyID CSSPropertyTestSinkPriority = CSSPropertyID::TestSinkPriority;
inline constexpr CSSPropertyID CSSPropertyTestLogicalPropertyGroupPhysicalHorizontal = CSSPropertyID::TestLogicalPropertyGroupPhysicalHorizontal;
inline constexpr CSSPropertyID CSSPropertyTestLogicalPropertyGroupPhysicalVertical = CSSPropertyID::TestLogicalPropertyGroupPhysicalVertical;
inline constexpr CSSPropertyID CSSPropertyTestLogicalPropertyGroupLogicalBlock = CSSPropertyID::TestLogicalPropertyGroupLogicalBlock;
inline constexpr CSSPropertyID CSSPropertyTestLogicalPropertyGroupLogicalInline = CSSPropertyID::TestLogicalPropertyGroupLogicalInline;
inline constexpr CSSPropertyID CSSPropertyAll = CSSPropertyID::All;
inline constexpr CSSPropertyID CSSPropertyFont = CSSPropertyID::Font;
inline constexpr CSSPropertyID CSSPropertyTestShorthandOne = CSSPropertyID::TestShorthandOne;
inline constexpr CSSPropertyID CSSPropertyTestShorthandTwo = CSSPropertyID::TestShorthandTwo;

// Enum value of the first "real" CSS property, which excludes
// CSSPropertyID::Invalid and CSSPropertyID::Custom.
constexpr uint16_t firstCSSProperty = 2;
// Total number of enum values in the CSSPropertyID enum. If making an array
// that can be indexed into using the enum value, use this as the size.
constexpr uint16_t cssPropertyIDEnumValueCount = 121;
// Number of "real" CSS properties. This differs from cssPropertyIDEnumValueCount,
// as this doesn't consider CSSPropertyID::Invalid and CSSPropertyID::Custom.
constexpr uint16_t numCSSProperties = 119;
constexpr unsigned maxCSSPropertyNameLength = 114;
constexpr auto firstTopPriorityProperty = CSSPropertyID::TestTopPriority;
constexpr auto lastTopPriorityProperty = CSSPropertyID::TestTopPriority;
constexpr auto firstHighPriorityProperty = CSSPropertyID::TestHighPriority;
constexpr auto lastHighPriorityProperty = CSSPropertyID::TestHighPriority;
constexpr auto firstMediumPriorityProperty = CSSPropertyID::TestMediumPriority;
constexpr auto lastMediumPriorityProperty = CSSPropertyID::TestMediumPriority;
constexpr auto firstLowPriorityProperty = CSSPropertyID::BackgroundCoordinatedValueListPropertyTestDiscrete;
constexpr auto lastLowPriorityProperty = CSSPropertyID::TestSinkPriority;
constexpr auto firstLogicalGroupPhysicalProperty = CSSPropertyID::TestLogicalPropertyGroupPhysicalHorizontal;
constexpr auto lastLogicalGroupPhysicalProperty = CSSPropertyID::TestLogicalPropertyGroupPhysicalVertical;
constexpr auto firstLogicalGroupLogicalProperty = CSSPropertyID::TestLogicalPropertyGroupLogicalBlock;
constexpr auto lastLogicalGroupLogicalProperty = CSSPropertyID::TestLogicalPropertyGroupLogicalInline;
constexpr auto firstLogicalGroupProperty = firstLogicalGroupPhysicalProperty;
constexpr auto lastLogicalGroupProperty = lastLogicalGroupLogicalProperty;
constexpr auto firstShorthandProperty = CSSPropertyID::All;
constexpr auto lastShorthandProperty = CSSPropertyID::TestShorthandTwo;
constexpr uint16_t numCSSPropertyLonghands = std::to_underlying(firstShorthandProperty) - firstCSSProperty;

extern const std::array<CSSPropertyID, 23> computedPropertyIDs;

template<CSSPropertyID C> struct PropertyNameConstant {
    static constexpr auto value = C;
    constexpr bool operator==(const PropertyNameConstant&) const = default;
    constexpr bool operator==(CSSPropertyID other) const { return value == other; }
};

struct CSSPropertySettings {
    WTF_DEPRECATED_MAKE_STRUCT_FAST_ALLOCATED(CSSPropertySettings);

    bool cssDescriptorEnabled : 1 { false };
    bool cssSettingsOneEnabled : 1 { false };
    bool cssSettingsShorthandEnabled : 1 { false };

    CSSPropertySettings() = default;
    explicit CSSPropertySettings(const Settings&);
};

bool operator==(const CSSPropertySettings&, const CSSPropertySettings&);
void add(Hasher&, const CSSPropertySettings&);

constexpr bool isLonghand(CSSPropertyID);
bool isInternal(CSSPropertyID);
bool isExposed(CSSPropertyID, const Settings*);
bool isExposed(CSSPropertyID, const Settings&);
bool isExposed(CSSPropertyID, const CSSPropertySettings*);
bool isExposed(CSSPropertyID, const CSSPropertySettings&);

CSSPropertyID findCSSProperty(const char* characters, unsigned length);
ASCIILiteral nameLiteral(CSSPropertyID);
const AtomString& nameString(CSSPropertyID);
String nameForIDL(CSSPropertyID);

CSSPropertyID cascadeAliasProperty(CSSPropertyID);

template<CSSPropertyID first, CSSPropertyID last> struct CSSPropertiesRange {
    struct Iterator {
        uint16_t index { static_cast<uint16_t>(first) };
        constexpr CSSPropertyID operator*() const { return static_cast<CSSPropertyID>(index); }
        constexpr Iterator& operator++() { ++index; return *this; }
        constexpr bool operator==(std::nullptr_t) const { return index > static_cast<uint16_t>(last); }
    };
    static constexpr Iterator begin() { return { }; }
    static constexpr std::nullptr_t end() { return nullptr; }
    static constexpr uint16_t size() { return std::to_underlying(last) - std::to_underlying(first) + 1; }
};
using AllCSSPropertiesRange = CSSPropertiesRange<static_cast<CSSPropertyID>(firstCSSProperty), lastShorthandProperty>;
using AllLonghandCSSPropertiesRange = CSSPropertiesRange<static_cast<CSSPropertyID>(firstCSSProperty), lastLogicalGroupProperty>;
constexpr AllCSSPropertiesRange allCSSProperties() { return { }; }
constexpr AllLonghandCSSPropertiesRange allLonghandCSSProperties() { return { }; }

constexpr bool isLonghand(CSSPropertyID property)
{
    return static_cast<uint16_t>(property) >= firstCSSProperty
        && static_cast<uint16_t>(property) < static_cast<uint16_t>(firstShorthandProperty);
}
constexpr bool isShorthand(CSSPropertyID property)
{
    return static_cast<uint16_t>(property) >= static_cast<uint16_t>(firstShorthandProperty)
        && static_cast<uint16_t>(property) <= static_cast<uint16_t>(lastShorthandProperty);
}

constexpr bool isLogicalPropertyGroupProperty(CSSPropertyID property)
{
    return static_cast<uint16_t>(property) >= static_cast<uint16_t>(firstLogicalGroupPhysicalProperty)
        && static_cast<uint16_t>(property) <= static_cast<uint16_t>(lastLogicalGroupLogicalProperty);
}

constexpr bool isLogicalPropertyGroupPhysicalProperty(CSSPropertyID property)
{
    return static_cast<uint16_t>(property) >= static_cast<uint16_t>(firstLogicalGroupPhysicalProperty)
        && static_cast<uint16_t>(property) <= static_cast<uint16_t>(lastLogicalGroupPhysicalProperty);
}

constexpr bool isLogicalPropertyGroupLogicalProperty(CSSPropertyID property)
{
    return static_cast<uint16_t>(property) >= static_cast<uint16_t>(firstLogicalGroupLogicalProperty)
        && static_cast<uint16_t>(property) <= static_cast<uint16_t>(lastLogicalGroupLogicalProperty);
}

WTF::TextStream& operator<<(WTF::TextStream&, CSSPropertyID);

} // namespace WebCore

namespace WTF {

template<> struct DefaultHash<WebCore::CSSPropertyID> {
    static unsigned hash(WebCore::CSSPropertyID key) { return IntHash<unsigned>::hash(std::to_underlying(key)); }
    static bool equal(WebCore::CSSPropertyID a, WebCore::CSSPropertyID b) { return a == b; }
    static constexpr bool safeToCompareToEmptyOrDeleted = true;
};

template<> struct HashTraits<WebCore::CSSPropertyID> : GenericHashTraits<WebCore::CSSPropertyID> {
    static const bool emptyValueIsZero = true;
    static void constructDeletedValue(WebCore::CSSPropertyID& slot) { slot = static_cast<WebCore::CSSPropertyID>(std::numeric_limits<uint16_t>::max()); }
    static bool isDeletedValue(WebCore::CSSPropertyID value) { return static_cast<uint16_t>(value) == std::numeric_limits<uint16_t>::max(); }
};

} // namespace WTF

namespace std {

template<> struct iterator_traits<WebCore::AllCSSPropertiesRange::Iterator> { using value_type = WebCore::CSSPropertyID; };
template<> struct iterator_traits<WebCore::AllLonghandCSSPropertiesRange::Iterator> { using value_type = WebCore::CSSPropertyID; };

} // namespace std

