// This file is automatically generated from CSSProperties.json by the process-css-properties.py script. Do not edit it.

#pragma once

#include "CSSPrimitiveValue.h"
#include "CSSPropertyNames.h"
#include "CSSValueKeywords.h"
#include <wtf/Variant.h>

namespace WebCore {

using InitialValue = Variant<CSSValueID, CSSPrimitiveValue::Raw>;

static constexpr InitialValue initialValueForLonghand(CSSPropertyID longhand)
{
    switch (longhand) {
    case CSSPropertyID::BackgroundCoordinatedValueListPropertyTestDiscrete:
    case CSSPropertyID::BackgroundCoordinatedValueListPropertyTestTwo:
    case CSSPropertyID::TestAnimationWrapper:
    case CSSPropertyID::TestAnimationWrapperAccelerationAlways:
    case CSSPropertyID::TestAnimationWrapperAccelerationThreadedOnly:
    case CSSPropertyID::TestCustomExtractor:
    case CSSPropertyID::TestHighPriority:
    case CSSPropertyID::TestLogicalPropertyGroupPhysicalHorizontal:
    case CSSPropertyID::TestLogicalPropertyGroupPhysicalVertical:
    case CSSPropertyID::TestMatchOne:
    case CSSPropertyID::TestMatchOneWithGroupWithSettingsFlag:
    case CSSPropertyID::TestMatchOneWithKeywordWithSettingsFlag:
    case CSSPropertyID::TestMatchOneWithMultipleKeywords:
    case CSSPropertyID::TestMatchOneWithReferenceWithSettingsFlag:
    case CSSPropertyID::TestMediumPriority:
    case CSSPropertyID::TestNumericValueRange:
    case CSSPropertyID::TestProperty:
    case CSSPropertyID::TestRenderStyleHasExplicitlySetPolicyAllAuthorOrigin:
    case CSSPropertyID::TestRenderStyleHasExplicitlySetPolicyAllBorderRadius:
    case CSSPropertyID::TestRenderStyleHasExplicitlySetPolicyValueOnly:
    case CSSPropertyID::TestRenderStyleStorageOneLevelReference:
    case CSSPropertyID::TestRenderStyleStorageOneLevelValue:
    case CSSPropertyID::TestRenderStyleStorageTwoLevelReference:
    case CSSPropertyID::TestRenderStyleStorageTwoLevelValue:
    case CSSPropertyID::TestSettingsOne:
    case CSSPropertyID::TestSinkPriority:
    case CSSPropertyID::TestTopPriority:
    case CSSPropertyID::TestUsingSharedRule:
    case CSSPropertyID::TestUsingSharedRuleExported:
    case CSSPropertyID::TestUsingSharedRuleWithOverrideFunction:
        return CSSPrimitiveValue::Raw { CSSUnitType::Number, 0 };
    case CSSPropertyID::TestColor:
    case CSSPropertyID::TestColorAllowsTypesAbsolute:
    case CSSPropertyID::TestColorPropertyWithVisitedLinkSupport:
        return CSSValueCurrentColor;
    case CSSPropertyID::TestKeyword:
    case CSSPropertyID::TestKeywordWithAliasedTo:
    case CSSPropertyID::TestRenderStyleGetterNodeleteFalse:
    case CSSPropertyID::TestRenderStyleStorageOneLevelEnum:
    case CSSPropertyID::TestRenderStyleStorageOneLevelRaw:
    case CSSPropertyID::TestRenderStyleStorageTwoLevelEnum:
    case CSSPropertyID::TestRenderStyleStorageTwoLevelRaw:
        return CSSValueFoo;
    case CSSPropertyID::TestMatchOneWithSettingsFlag:
    case CSSPropertyID::TestUrlWithModifiers:
    case CSSPropertyID::TestUrlWithNoModifiers:
        return CSSValueNone;
    default:
        RELEASE_ASSERT_NOT_REACHED();
    }
}
} // namespace WebCore

