// This file is automatically generated from CSSProperties.json by the process-css-properties.py script. Do not edit it.

#include "config.h"
#include "StyleInterpolationWrapperMap.h"

#include "StylePropertyShorthand.h"

#define STYLE_INTERPOLATION_GENERATED_INCLUDE_TRAP 1
#include "StyleInterpolationWrappers.h"
#undef STYLE_INTERPOLATION_GENERATED_INCLUDE_TRAP
namespace WebCore {
namespace Style {
namespace Interpolation {

static WrapperBase* makeShorthandWrapper(CSSPropertyID id, const std::array<WrapperBase*, cssPropertyIDEnumValueCount>& wrappers)
{
    auto shorthand = shorthandForProperty(id);
    ASSERT(shorthand.length());

    auto longhandWrappers = WTF::compactMap(shorthand, [&](auto longhand) -> std::optional<WrapperBase*> {
        auto wrapper = wrappers[std::to_underlying(longhand)];
        if (!wrapper)
            return std::nullopt;
        return wrapper;
    });

    return new ShorthandWrapper(id, WTF::move(longhandWrappers));
}

WrapperMap::WrapperMap()
    : m_wrappers {
        nullptr, // CSSPropertyID::Invalid
        nullptr, // CSSPropertyID::Custom
        new DiscreteWrapper(CSSPropertyID::TestTopPriority, &ComputedStyle::testTopPriority, &ComputedStyle::setTestTopPriority), // CSSPropertyID::TestTopPriority
        new DiscreteWrapper(CSSPropertyID::TestHighPriority, &ComputedStyle::testHighPriority, &ComputedStyle::setTestHighPriority), // CSSPropertyID::TestHighPriority
        new DiscreteWrapper(CSSPropertyID::TestMediumPriority, &ComputedStyle::testMediumPriority, &ComputedStyle::setTestMediumPriority), // CSSPropertyID::TestMediumPriority
        new CoordinatedValueListPropertyWrapper(PropertyNameConstant<CSSPropertyID::BackgroundCoordinatedValueListPropertyTestDiscrete> { }, &ComputedStyle::backgroundLayers, &ComputedStyle::ensureBackgroundLayers, &ComputedStyle::setBackgroundLayers, DiscreteCoordinatedValueListPropertyWrapper(CSSPropertyID::BackgroundCoordinatedValueListPropertyTestDiscrete, &BackgroundLayers::value_type::backgroundCoordinatedValueListPropertyTestDiscrete, &BackgroundLayers::value_type::setBackgroundCoordinatedValueListPropertyTestDiscrete)), // CSSPropertyID::BackgroundCoordinatedValueListPropertyTestDiscrete
        new CoordinatedValueListPropertyWrapper(PropertyNameConstant<CSSPropertyID::BackgroundCoordinatedValueListPropertyTestTwo> { }, &ComputedStyle::backgroundLayers, &ComputedStyle::ensureBackgroundLayers, &ComputedStyle::setBackgroundLayers, DiscreteCoordinatedValueListPropertyWrapper(CSSPropertyID::BackgroundCoordinatedValueListPropertyTestTwo, &BackgroundLayers::value_type::backgroundCoordinatedValueListPropertyTestTwo, &BackgroundLayers::value_type::setBackgroundCoordinatedValueListPropertyTestTwo)), // CSSPropertyID::BackgroundCoordinatedValueListPropertyTestTwo
        nullptr, // CSSPropertyID::FirstTestDescriptorForFirstDescriptor - not animatable (descriptor only)
        nullptr, // CSSPropertyID::FirstTestDescriptorForSecondDescriptor - not animatable (descriptor only)
        new Wrapper<float>(CSSPropertyID::TestAnimationWrapper, &ComputedStyle::testAnimationWrapper, &ComputedStyle::setTestAnimationWrapper), // CSSPropertyID::TestAnimationWrapper
        new Wrapper<float>(CSSPropertyID::TestAnimationWrapperAccelerationAlways, &ComputedStyle::testAnimationWrapperAccelerationAlways, &ComputedStyle::setTestAnimationWrapperAccelerationAlways), // CSSPropertyID::TestAnimationWrapperAccelerationAlways
        new Wrapper<float>(CSSPropertyID::TestAnimationWrapperAccelerationThreadedOnly, &ComputedStyle::testAnimationWrapperAccelerationThreadedOnly, &ComputedStyle::setTestAnimationWrapperAccelerationThreadedOnly), // CSSPropertyID::TestAnimationWrapperAccelerationThreadedOnly
        new DiscreteWrapper(CSSPropertyID::TestBoundedRepetitionWithCommas, &ComputedStyle::testBoundedRepetitionWithCommas, &ComputedStyle::setTestBoundedRepetitionWithCommas), // CSSPropertyID::TestBoundedRepetitionWithCommas
        new DiscreteWrapper(CSSPropertyID::TestBoundedRepetitionWithCommasFixed, &ComputedStyle::testBoundedRepetitionWithCommasFixed, &ComputedStyle::setTestBoundedRepetitionWithCommasFixed), // CSSPropertyID::TestBoundedRepetitionWithCommasFixed
        new DiscreteWrapper(CSSPropertyID::TestBoundedRepetitionWithCommasNoSingleItemOpt, &ComputedStyle::testBoundedRepetitionWithCommasNoSingleItemOpt, &ComputedStyle::setTestBoundedRepetitionWithCommasNoSingleItemOpt), // CSSPropertyID::TestBoundedRepetitionWithCommasNoSingleItemOpt
        new DiscreteWrapper(CSSPropertyID::TestBoundedRepetitionWithCommasSingleItemOpt, &ComputedStyle::testBoundedRepetitionWithCommasSingleItemOpt, &ComputedStyle::setTestBoundedRepetitionWithCommasSingleItemOpt), // CSSPropertyID::TestBoundedRepetitionWithCommasSingleItemOpt
        new DiscreteWrapper(CSSPropertyID::TestBoundedRepetitionWithSpaces, &ComputedStyle::testBoundedRepetitionWithSpaces, &ComputedStyle::setTestBoundedRepetitionWithSpaces), // CSSPropertyID::TestBoundedRepetitionWithSpaces
        new DiscreteWrapper(CSSPropertyID::TestBoundedRepetitionWithSpacesFixed, &ComputedStyle::testBoundedRepetitionWithSpacesFixed, &ComputedStyle::setTestBoundedRepetitionWithSpacesFixed), // CSSPropertyID::TestBoundedRepetitionWithSpacesFixed
        new DiscreteWrapper(CSSPropertyID::TestBoundedRepetitionWithSpacesNoSingleItemOpt, &ComputedStyle::testBoundedRepetitionWithSpacesNoSingleItemOpt, &ComputedStyle::setTestBoundedRepetitionWithSpacesNoSingleItemOpt), // CSSPropertyID::TestBoundedRepetitionWithSpacesNoSingleItemOpt
        new DiscreteWrapper(CSSPropertyID::TestBoundedRepetitionWithSpacesSingleItemOpt, &ComputedStyle::testBoundedRepetitionWithSpacesSingleItemOpt, &ComputedStyle::setTestBoundedRepetitionWithSpacesSingleItemOpt), // CSSPropertyID::TestBoundedRepetitionWithSpacesSingleItemOpt
        new DiscreteWrapper(CSSPropertyID::TestBoundedRepetitionWithSpacesWithType, &ComputedStyle::testBoundedRepetitionWithSpacesWithType, &ComputedStyle::setTestBoundedRepetitionWithSpacesWithType), // CSSPropertyID::TestBoundedRepetitionWithSpacesWithType
        new DiscreteWrapper(CSSPropertyID::TestBoundedRepetitionWithSpacesWithTypeNoSingleItemOpt, &ComputedStyle::testBoundedRepetitionWithSpacesWithTypeNoSingleItemOpt, &ComputedStyle::setTestBoundedRepetitionWithSpacesWithTypeNoSingleItemOpt), // CSSPropertyID::TestBoundedRepetitionWithSpacesWithTypeNoSingleItemOpt
        new DiscreteWrapper(CSSPropertyID::TestBoundedRepetitionWithSpacesWithTypeWithDefaultPrevious, &ComputedStyle::testBoundedRepetitionWithSpacesWithTypeWithDefaultPrevious, &ComputedStyle::setTestBoundedRepetitionWithSpacesWithTypeWithDefaultPrevious), // CSSPropertyID::TestBoundedRepetitionWithSpacesWithTypeWithDefaultPrevious
        new DiscreteWrapper(CSSPropertyID::TestBoundedRepetitionWithSpacesWithTypeWithDefaultPreviousTwo, &ComputedStyle::testBoundedRepetitionWithSpacesWithTypeWithDefaultPreviousTwo, &ComputedStyle::setTestBoundedRepetitionWithSpacesWithTypeWithDefaultPreviousTwo), // CSSPropertyID::TestBoundedRepetitionWithSpacesWithTypeWithDefaultPreviousTwo
        new StyleTypeWrapper(CSSPropertyID::TestColor, &ComputedStyle::testColor, &ComputedStyle::setTestColor), // CSSPropertyID::TestColor
        new StyleTypeWrapper(CSSPropertyID::TestColorAllowsTypesAbsolute, &ComputedStyle::testColorAllowsTypesAbsolute, &ComputedStyle::setTestColorAllowsTypesAbsolute), // CSSPropertyID::TestColorAllowsTypesAbsolute
        new VisitedAffectedStyleTypeWrapper(CSSPropertyID::TestColorPropertyWithVisitedLinkSupport, &ComputedStyle::testColorPropertyWithVisitedLinkSupport, &ComputedStyle::setTestColorPropertyWithVisitedLinkSupport, &ComputedStyle::visitedLinkTestColorPropertyWithVisitedLinkSupport, &ComputedStyle::setVisitedLinkTestColorPropertyWithVisitedLinkSupport), // CSSPropertyID::TestColorPropertyWithVisitedLinkSupport
        new DiscreteWrapper(CSSPropertyID::TestCustomExtractor, &ComputedStyle::testCustomExtractor, &ComputedStyle::setTestCustomExtractor), // CSSPropertyID::TestCustomExtractor
        new DiscreteWrapper(CSSPropertyID::TestFunctionBoundedParameters, &ComputedStyle::testFunctionBoundedParameters, &ComputedStyle::setTestFunctionBoundedParameters), // CSSPropertyID::TestFunctionBoundedParameters
        new DiscreteWrapper(CSSPropertyID::TestFunctionFixedParameters, &ComputedStyle::testFunctionFixedParameters, &ComputedStyle::setTestFunctionFixedParameters), // CSSPropertyID::TestFunctionFixedParameters
        new DiscreteWrapper(CSSPropertyID::TestFunctionNoParameters, &ComputedStyle::testFunctionNoParameters, &ComputedStyle::setTestFunctionNoParameters), // CSSPropertyID::TestFunctionNoParameters
        new DiscreteWrapper(CSSPropertyID::TestFunctionParametersMatchAllAnyOrder, &ComputedStyle::testFunctionParametersMatchAllAnyOrder, &ComputedStyle::setTestFunctionParametersMatchAllAnyOrder), // CSSPropertyID::TestFunctionParametersMatchAllAnyOrder
        new DiscreteWrapper(CSSPropertyID::TestFunctionParametersMatchAllAnyOrderWithOptional, &ComputedStyle::testFunctionParametersMatchAllAnyOrderWithOptional, &ComputedStyle::setTestFunctionParametersMatchAllAnyOrderWithOptional), // CSSPropertyID::TestFunctionParametersMatchAllAnyOrderWithOptional
        new DiscreteWrapper(CSSPropertyID::TestFunctionParametersMatchAllOrdered, &ComputedStyle::testFunctionParametersMatchAllOrdered, &ComputedStyle::setTestFunctionParametersMatchAllOrdered), // CSSPropertyID::TestFunctionParametersMatchAllOrdered
        new DiscreteWrapper(CSSPropertyID::TestFunctionParametersMatchAllOrderedWithOptional, &ComputedStyle::testFunctionParametersMatchAllOrderedWithOptional, &ComputedStyle::setTestFunctionParametersMatchAllOrderedWithOptional), // CSSPropertyID::TestFunctionParametersMatchAllOrderedWithOptional
        new DiscreteWrapper(CSSPropertyID::TestFunctionParametersMatchOneOrMoreAnyOrder, &ComputedStyle::testFunctionParametersMatchOneOrMoreAnyOrder, &ComputedStyle::setTestFunctionParametersMatchOneOrMoreAnyOrder), // CSSPropertyID::TestFunctionParametersMatchOneOrMoreAnyOrder
        new DiscreteWrapper(CSSPropertyID::TestFunctionSingleParameter, &ComputedStyle::testFunctionSingleParameter, &ComputedStyle::setTestFunctionSingleParameter), // CSSPropertyID::TestFunctionSingleParameter
        new DiscreteWrapper(CSSPropertyID::TestFunctionSingleParameterMatchOne, &ComputedStyle::testFunctionSingleParameterMatchOne, &ComputedStyle::setTestFunctionSingleParameterMatchOne), // CSSPropertyID::TestFunctionSingleParameterMatchOne
        new DiscreteWrapper(CSSPropertyID::TestFunctionSingleParameterOptional, &ComputedStyle::testFunctionSingleParameterOptional, &ComputedStyle::setTestFunctionSingleParameterOptional), // CSSPropertyID::TestFunctionSingleParameterOptional
        new DiscreteWrapper(CSSPropertyID::TestFunctionUnboundedParametersNoMin, &ComputedStyle::testFunctionUnboundedParametersNoMin, &ComputedStyle::setTestFunctionUnboundedParametersNoMin), // CSSPropertyID::TestFunctionUnboundedParametersNoMin
        new DiscreteWrapper(CSSPropertyID::TestFunctionUnboundedParametersWithMinimum, &ComputedStyle::testFunctionUnboundedParametersWithMinimum, &ComputedStyle::setTestFunctionUnboundedParametersWithMinimum), // CSSPropertyID::TestFunctionUnboundedParametersWithMinimum
        new DiscreteWrapper(CSSPropertyID::TestImage, &ComputedStyle::testImage, &ComputedStyle::setTestImage), // CSSPropertyID::TestImage
        new DiscreteWrapper(CSSPropertyID::TestImageNoImageSet, &ComputedStyle::testImageNoImageSet, &ComputedStyle::setTestImageNoImageSet), // CSSPropertyID::TestImageNoImageSet
        new DiscreteWrapper(CSSPropertyID::TestKeyword, &ComputedStyle::testKeyword, &ComputedStyle::setTestKeyword), // CSSPropertyID::TestKeyword
        new DiscreteWrapper(CSSPropertyID::TestKeywordWithAliasedTo, &ComputedStyle::testKeywordWithAliasedTo, &ComputedStyle::setTestKeywordWithAliasedTo), // CSSPropertyID::TestKeywordWithAliasedTo
        new DiscreteWrapper(CSSPropertyID::TestMatchAllAnyOrder, &ComputedStyle::testMatchAllAnyOrder, &ComputedStyle::setTestMatchAllAnyOrder), // CSSPropertyID::TestMatchAllAnyOrder
        new DiscreteWrapper(CSSPropertyID::TestMatchAllAnyOrderWithCustomType, &ComputedStyle::testMatchAllAnyOrderWithCustomType, &ComputedStyle::setTestMatchAllAnyOrderWithCustomType), // CSSPropertyID::TestMatchAllAnyOrderWithCustomType
        new DiscreteWrapper(CSSPropertyID::TestMatchAllAnyOrderWithOptional, &ComputedStyle::testMatchAllAnyOrderWithOptional, &ComputedStyle::setTestMatchAllAnyOrderWithOptional), // CSSPropertyID::TestMatchAllAnyOrderWithOptional
        new DiscreteWrapper(CSSPropertyID::TestMatchAllAnyOrderWithOptionalAndCustomType, &ComputedStyle::testMatchAllAnyOrderWithOptionalAndCustomType, &ComputedStyle::setTestMatchAllAnyOrderWithOptionalAndCustomType), // CSSPropertyID::TestMatchAllAnyOrderWithOptionalAndCustomType
        new DiscreteWrapper(CSSPropertyID::TestMatchAllAnyOrderWithOptionalAndMultipleRequiredAndCustomType, &ComputedStyle::testMatchAllAnyOrderWithOptionalAndMultipleRequiredAndCustomType, &ComputedStyle::setTestMatchAllAnyOrderWithOptionalAndMultipleRequiredAndCustomType), // CSSPropertyID::TestMatchAllAnyOrderWithOptionalAndMultipleRequiredAndCustomType
        new DiscreteWrapper(CSSPropertyID::TestMatchAllAnyOrderWithOptionalAndMultipleRequiredAndCustomTypeNoSingleItemOpt, &ComputedStyle::testMatchAllAnyOrderWithOptionalAndMultipleRequiredAndCustomTypeNoSingleItemOpt, &ComputedStyle::setTestMatchAllAnyOrderWithOptionalAndMultipleRequiredAndCustomTypeNoSingleItemOpt), // CSSPropertyID::TestMatchAllAnyOrderWithOptionalAndMultipleRequiredAndCustomTypeNoSingleItemOpt
        new DiscreteWrapper(CSSPropertyID::TestMatchAllAnyOrderWithOptionalAndMultipleRequiredAndPreserveOrderAndCustomType, &ComputedStyle::testMatchAllAnyOrderWithOptionalAndMultipleRequiredAndPreserveOrderAndCustomType, &ComputedStyle::setTestMatchAllAnyOrderWithOptionalAndMultipleRequiredAndPreserveOrderAndCustomType), // CSSPropertyID::TestMatchAllAnyOrderWithOptionalAndMultipleRequiredAndPreserveOrderAndCustomType
        new DiscreteWrapper(CSSPropertyID::TestMatchAllAnyOrderWithOptionalAndMultipleRequiredAndPreserveOrderAndCustomTypeNoSingleItemOpt, &ComputedStyle::testMatchAllAnyOrderWithOptionalAndMultipleRequiredAndPreserveOrderAndCustomTypeNoSingleItemOpt, &ComputedStyle::setTestMatchAllAnyOrderWithOptionalAndMultipleRequiredAndPreserveOrderAndCustomTypeNoSingleItemOpt), // CSSPropertyID::TestMatchAllAnyOrderWithOptionalAndMultipleRequiredAndPreserveOrderAndCustomTypeNoSingleItemOpt
        new DiscreteWrapper(CSSPropertyID::TestMatchAllAnyOrderWithOptionalAndPreserveOrderAndCustomType, &ComputedStyle::testMatchAllAnyOrderWithOptionalAndPreserveOrderAndCustomType, &ComputedStyle::setTestMatchAllAnyOrderWithOptionalAndPreserveOrderAndCustomType), // CSSPropertyID::TestMatchAllAnyOrderWithOptionalAndPreserveOrderAndCustomType
        new DiscreteWrapper(CSSPropertyID::TestMatchAllAnyOrderWithOptionalNoSingleItemOpt, &ComputedStyle::testMatchAllAnyOrderWithOptionalNoSingleItemOpt, &ComputedStyle::setTestMatchAllAnyOrderWithOptionalNoSingleItemOpt), // CSSPropertyID::TestMatchAllAnyOrderWithOptionalNoSingleItemOpt
        new DiscreteWrapper(CSSPropertyID::TestMatchAllAnyOrderWithOptionalSingleItemOpt, &ComputedStyle::testMatchAllAnyOrderWithOptionalSingleItemOpt, &ComputedStyle::setTestMatchAllAnyOrderWithOptionalSingleItemOpt), // CSSPropertyID::TestMatchAllAnyOrderWithOptionalSingleItemOpt
        new DiscreteWrapper(CSSPropertyID::TestMatchAllAnyOrderWithOptionalWithPreserveOrder, &ComputedStyle::testMatchAllAnyOrderWithOptionalWithPreserveOrder, &ComputedStyle::setTestMatchAllAnyOrderWithOptionalWithPreserveOrder), // CSSPropertyID::TestMatchAllAnyOrderWithOptionalWithPreserveOrder
        new DiscreteWrapper(CSSPropertyID::TestMatchAllAnyOrderWithOptionalWithPreserveOrderNoSingleItemOpt, &ComputedStyle::testMatchAllAnyOrderWithOptionalWithPreserveOrderNoSingleItemOpt, &ComputedStyle::setTestMatchAllAnyOrderWithOptionalWithPreserveOrderNoSingleItemOpt), // CSSPropertyID::TestMatchAllAnyOrderWithOptionalWithPreserveOrderNoSingleItemOpt
        new DiscreteWrapper(CSSPropertyID::TestMatchAllAnyOrderWithPreserveOrder, &ComputedStyle::testMatchAllAnyOrderWithPreserveOrder, &ComputedStyle::setTestMatchAllAnyOrderWithPreserveOrder), // CSSPropertyID::TestMatchAllAnyOrderWithPreserveOrder
        new DiscreteWrapper(CSSPropertyID::TestMatchAllAnyOrderWithPreserveOrderAndCustomType, &ComputedStyle::testMatchAllAnyOrderWithPreserveOrderAndCustomType, &ComputedStyle::setTestMatchAllAnyOrderWithPreserveOrderAndCustomType), // CSSPropertyID::TestMatchAllAnyOrderWithPreserveOrderAndCustomType
        new DiscreteWrapper(CSSPropertyID::TestMatchAllAnyOrderWithPreserveOrderNoSingleItemOpt, &ComputedStyle::testMatchAllAnyOrderWithPreserveOrderNoSingleItemOpt, &ComputedStyle::setTestMatchAllAnyOrderWithPreserveOrderNoSingleItemOpt), // CSSPropertyID::TestMatchAllAnyOrderWithPreserveOrderNoSingleItemOpt
        new DiscreteWrapper(CSSPropertyID::TestMatchAllOrdered, &ComputedStyle::testMatchAllOrdered, &ComputedStyle::setTestMatchAllOrdered), // CSSPropertyID::TestMatchAllOrdered
        new DiscreteWrapper(CSSPropertyID::TestMatchAllOrderedWithCustomType, &ComputedStyle::testMatchAllOrderedWithCustomType, &ComputedStyle::setTestMatchAllOrderedWithCustomType), // CSSPropertyID::TestMatchAllOrderedWithCustomType
        new DiscreteWrapper(CSSPropertyID::TestMatchAllOrderedWithOptional, &ComputedStyle::testMatchAllOrderedWithOptional, &ComputedStyle::setTestMatchAllOrderedWithOptional), // CSSPropertyID::TestMatchAllOrderedWithOptional
        new DiscreteWrapper(CSSPropertyID::TestMatchAllOrderedWithOptionalAndCustomType, &ComputedStyle::testMatchAllOrderedWithOptionalAndCustomType, &ComputedStyle::setTestMatchAllOrderedWithOptionalAndCustomType), // CSSPropertyID::TestMatchAllOrderedWithOptionalAndCustomType
        new DiscreteWrapper(CSSPropertyID::TestMatchAllOrderedWithOptionalAndCustomTypeAndNoSingleItemOpt, &ComputedStyle::testMatchAllOrderedWithOptionalAndCustomTypeAndNoSingleItemOpt, &ComputedStyle::setTestMatchAllOrderedWithOptionalAndCustomTypeAndNoSingleItemOpt), // CSSPropertyID::TestMatchAllOrderedWithOptionalAndCustomTypeAndNoSingleItemOpt
        new DiscreteWrapper(CSSPropertyID::TestMatchAllOrderedWithOptionalAndMultipleRequired, &ComputedStyle::testMatchAllOrderedWithOptionalAndMultipleRequired, &ComputedStyle::setTestMatchAllOrderedWithOptionalAndMultipleRequired), // CSSPropertyID::TestMatchAllOrderedWithOptionalAndMultipleRequired
        new DiscreteWrapper(CSSPropertyID::TestMatchAllOrderedWithOptionalAndMultipleRequiredAndCustomType, &ComputedStyle::testMatchAllOrderedWithOptionalAndMultipleRequiredAndCustomType, &ComputedStyle::setTestMatchAllOrderedWithOptionalAndMultipleRequiredAndCustomType), // CSSPropertyID::TestMatchAllOrderedWithOptionalAndMultipleRequiredAndCustomType
        new DiscreteWrapper(CSSPropertyID::TestMatchAllOrderedWithOptionalNoSingleItemOpt, &ComputedStyle::testMatchAllOrderedWithOptionalNoSingleItemOpt, &ComputedStyle::setTestMatchAllOrderedWithOptionalNoSingleItemOpt), // CSSPropertyID::TestMatchAllOrderedWithOptionalNoSingleItemOpt
        new DiscreteWrapper(CSSPropertyID::TestMatchAllOrderedWithOptionalSingleItemOpt, &ComputedStyle::testMatchAllOrderedWithOptionalSingleItemOpt, &ComputedStyle::setTestMatchAllOrderedWithOptionalSingleItemOpt), // CSSPropertyID::TestMatchAllOrderedWithOptionalSingleItemOpt
        new DiscreteWrapper(CSSPropertyID::TestMatchOne, &ComputedStyle::testMatchOne, &ComputedStyle::setTestMatchOne), // CSSPropertyID::TestMatchOne
        new DiscreteWrapper(CSSPropertyID::TestMatchOneOrMoreAnyOrder, &ComputedStyle::testMatchOneOrMoreAnyOrder, &ComputedStyle::setTestMatchOneOrMoreAnyOrder), // CSSPropertyID::TestMatchOneOrMoreAnyOrder
        new DiscreteWrapper(CSSPropertyID::TestMatchOneOrMoreAnyOrderNoSingleItemOpt, &ComputedStyle::testMatchOneOrMoreAnyOrderNoSingleItemOpt, &ComputedStyle::setTestMatchOneOrMoreAnyOrderNoSingleItemOpt), // CSSPropertyID::TestMatchOneOrMoreAnyOrderNoSingleItemOpt
        new DiscreteWrapper(CSSPropertyID::TestMatchOneOrMoreAnyOrderWithCustomType, &ComputedStyle::testMatchOneOrMoreAnyOrderWithCustomType, &ComputedStyle::setTestMatchOneOrMoreAnyOrderWithCustomType), // CSSPropertyID::TestMatchOneOrMoreAnyOrderWithCustomType
        new DiscreteWrapper(CSSPropertyID::TestMatchOneOrMoreAnyOrderWithCustomTypeNoSingleItemOpt, &ComputedStyle::testMatchOneOrMoreAnyOrderWithCustomTypeNoSingleItemOpt, &ComputedStyle::setTestMatchOneOrMoreAnyOrderWithCustomTypeNoSingleItemOpt), // CSSPropertyID::TestMatchOneOrMoreAnyOrderWithCustomTypeNoSingleItemOpt
        new DiscreteWrapper(CSSPropertyID::TestMatchOneOrMoreAnyOrderWithPreserveOrder, &ComputedStyle::testMatchOneOrMoreAnyOrderWithPreserveOrder, &ComputedStyle::setTestMatchOneOrMoreAnyOrderWithPreserveOrder), // CSSPropertyID::TestMatchOneOrMoreAnyOrderWithPreserveOrder
        new DiscreteWrapper(CSSPropertyID::TestMatchOneOrMoreAnyOrderWithPreserveOrderAndCustomType, &ComputedStyle::testMatchOneOrMoreAnyOrderWithPreserveOrderAndCustomType, &ComputedStyle::setTestMatchOneOrMoreAnyOrderWithPreserveOrderAndCustomType), // CSSPropertyID::TestMatchOneOrMoreAnyOrderWithPreserveOrderAndCustomType
        new DiscreteWrapper(CSSPropertyID::TestMatchOneOrMoreAnyOrderWithPreserveOrderAndCustomTypeNoSingleItemOpt, &ComputedStyle::testMatchOneOrMoreAnyOrderWithPreserveOrderAndCustomTypeNoSingleItemOpt, &ComputedStyle::setTestMatchOneOrMoreAnyOrderWithPreserveOrderAndCustomTypeNoSingleItemOpt), // CSSPropertyID::TestMatchOneOrMoreAnyOrderWithPreserveOrderAndCustomTypeNoSingleItemOpt
        new DiscreteWrapper(CSSPropertyID::TestMatchOneOrMoreAnyOrderWithPreserveOrderNoSingleItemOpt, &ComputedStyle::testMatchOneOrMoreAnyOrderWithPreserveOrderNoSingleItemOpt, &ComputedStyle::setTestMatchOneOrMoreAnyOrderWithPreserveOrderNoSingleItemOpt), // CSSPropertyID::TestMatchOneOrMoreAnyOrderWithPreserveOrderNoSingleItemOpt
        new DiscreteWrapper(CSSPropertyID::TestMatchOneWithGroupWithSettingsFlag, &ComputedStyle::testMatchOneWithGroupWithSettingsFlag, &ComputedStyle::setTestMatchOneWithGroupWithSettingsFlag), // CSSPropertyID::TestMatchOneWithGroupWithSettingsFlag
        new DiscreteWrapper(CSSPropertyID::TestMatchOneWithKeywordWithSettingsFlag, &ComputedStyle::testMatchOneWithKeywordWithSettingsFlag, &ComputedStyle::setTestMatchOneWithKeywordWithSettingsFlag), // CSSPropertyID::TestMatchOneWithKeywordWithSettingsFlag
        new DiscreteWrapper(CSSPropertyID::TestMatchOneWithMultipleKeywords, &ComputedStyle::testMatchOneWithMultipleKeywords, &ComputedStyle::setTestMatchOneWithMultipleKeywords), // CSSPropertyID::TestMatchOneWithMultipleKeywords
        new DiscreteWrapper(CSSPropertyID::TestMatchOneWithReferenceWithSettingsFlag, &ComputedStyle::testMatchOneWithReferenceWithSettingsFlag, &ComputedStyle::setTestMatchOneWithReferenceWithSettingsFlag), // CSSPropertyID::TestMatchOneWithReferenceWithSettingsFlag
        new DiscreteWrapper(CSSPropertyID::TestMatchOneWithSettingsFlag, &ComputedStyle::testMatchOneWithSettingsFlag, &ComputedStyle::setTestMatchOneWithSettingsFlag), // CSSPropertyID::TestMatchOneWithSettingsFlag
        new DiscreteWrapper(CSSPropertyID::TestNumericValueRange, &ComputedStyle::testNumericValueRange, &ComputedStyle::setTestNumericValueRange), // CSSPropertyID::TestNumericValueRange
        new DiscreteWrapper(CSSPropertyID::TestProperty, &ComputedStyle::testProperty, &ComputedStyle::setTestProperty), // CSSPropertyID::TestProperty
        new DiscreteWrapper(CSSPropertyID::TestRenderStyleGetterNodeleteFalse, &ComputedStyle::testRenderStyleGetterNodeleteFalse, &ComputedStyle::setTestRenderStyleGetterNodeleteFalse), // CSSPropertyID::TestRenderStyleGetterNodeleteFalse
        new DiscreteWrapper(CSSPropertyID::TestRenderStyleHasExplicitlySetPolicyAllAuthorOrigin, &ComputedStyle::testRenderStyleHasExplicitlySetPolicyAllAuthorOrigin, &ComputedStyle::setTestRenderStyleHasExplicitlySetPolicyAllAuthorOrigin), // CSSPropertyID::TestRenderStyleHasExplicitlySetPolicyAllAuthorOrigin
        new DiscreteWrapper(CSSPropertyID::TestRenderStyleHasExplicitlySetPolicyAllBorderRadius, &ComputedStyle::testRenderStyleHasExplicitlySetPolicyAllBorderRadius, &ComputedStyle::setTestRenderStyleHasExplicitlySetPolicyAllBorderRadius), // CSSPropertyID::TestRenderStyleHasExplicitlySetPolicyAllBorderRadius
        new DiscreteWrapper(CSSPropertyID::TestRenderStyleHasExplicitlySetPolicyValueOnly, &ComputedStyle::testRenderStyleHasExplicitlySetPolicyValueOnly, &ComputedStyle::setTestRenderStyleHasExplicitlySetPolicyValueOnly), // CSSPropertyID::TestRenderStyleHasExplicitlySetPolicyValueOnly
        new DiscreteWrapper(CSSPropertyID::TestRenderStyleStorageOneLevelEnum, &ComputedStyle::testRenderStyleStorageOneLevelEnum, &ComputedStyle::setTestRenderStyleStorageOneLevelEnum), // CSSPropertyID::TestRenderStyleStorageOneLevelEnum
        new DiscreteWrapper(CSSPropertyID::TestRenderStyleStorageOneLevelRaw, &ComputedStyle::testRenderStyleStorageOneLevelRaw, &ComputedStyle::setTestRenderStyleStorageOneLevelRaw), // CSSPropertyID::TestRenderStyleStorageOneLevelRaw
        new DiscreteWrapper(CSSPropertyID::TestRenderStyleStorageOneLevelReference, &ComputedStyle::testRenderStyleStorageOneLevelReference, &ComputedStyle::setTestRenderStyleStorageOneLevelReference), // CSSPropertyID::TestRenderStyleStorageOneLevelReference
        new DiscreteWrapper(CSSPropertyID::TestRenderStyleStorageOneLevelValue, &ComputedStyle::testRenderStyleStorageOneLevelValue, &ComputedStyle::setTestRenderStyleStorageOneLevelValue), // CSSPropertyID::TestRenderStyleStorageOneLevelValue
        new DiscreteWrapper(CSSPropertyID::TestRenderStyleStorageTwoLevelEnum, &ComputedStyle::testRenderStyleStorageTwoLevelEnum, &ComputedStyle::setTestRenderStyleStorageTwoLevelEnum), // CSSPropertyID::TestRenderStyleStorageTwoLevelEnum
        new DiscreteWrapper(CSSPropertyID::TestRenderStyleStorageTwoLevelRaw, &ComputedStyle::testRenderStyleStorageTwoLevelRaw, &ComputedStyle::setTestRenderStyleStorageTwoLevelRaw), // CSSPropertyID::TestRenderStyleStorageTwoLevelRaw
        new DiscreteWrapper(CSSPropertyID::TestRenderStyleStorageTwoLevelReference, &ComputedStyle::testRenderStyleStorageTwoLevelReference, &ComputedStyle::setTestRenderStyleStorageTwoLevelReference), // CSSPropertyID::TestRenderStyleStorageTwoLevelReference
        new DiscreteWrapper(CSSPropertyID::TestRenderStyleStorageTwoLevelValue, &ComputedStyle::testRenderStyleStorageTwoLevelValue, &ComputedStyle::setTestRenderStyleStorageTwoLevelValue), // CSSPropertyID::TestRenderStyleStorageTwoLevelValue
        new DiscreteWrapper(CSSPropertyID::TestSettingsOne, &ComputedStyle::testSettingsOne, &ComputedStyle::setTestSettingsOne), // CSSPropertyID::TestSettingsOne
        new DiscreteWrapper(CSSPropertyID::TestUnboundedRepetitionWithCommasWithMin, &ComputedStyle::testUnboundedRepetitionWithCommasWithMin, &ComputedStyle::setTestUnboundedRepetitionWithCommasWithMin), // CSSPropertyID::TestUnboundedRepetitionWithCommasWithMin
        new DiscreteWrapper(CSSPropertyID::TestUnboundedRepetitionWithCommasWithMinNoSingleItemOpt, &ComputedStyle::testUnboundedRepetitionWithCommasWithMinNoSingleItemOpt, &ComputedStyle::setTestUnboundedRepetitionWithCommasWithMinNoSingleItemOpt), // CSSPropertyID::TestUnboundedRepetitionWithCommasWithMinNoSingleItemOpt
        new DiscreteWrapper(CSSPropertyID::TestUnboundedRepetitionWithCommasWithMinSingleItemOpt, &ComputedStyle::testUnboundedRepetitionWithCommasWithMinSingleItemOpt, &ComputedStyle::setTestUnboundedRepetitionWithCommasWithMinSingleItemOpt), // CSSPropertyID::TestUnboundedRepetitionWithCommasWithMinSingleItemOpt
        new DiscreteWrapper(CSSPropertyID::TestUnboundedRepetitionWithSpacesNoMin, &ComputedStyle::testUnboundedRepetitionWithSpacesNoMin, &ComputedStyle::setTestUnboundedRepetitionWithSpacesNoMin), // CSSPropertyID::TestUnboundedRepetitionWithSpacesNoMin
        new DiscreteWrapper(CSSPropertyID::TestUnboundedRepetitionWithSpacesNoMinNoSingleItemOpt, &ComputedStyle::testUnboundedRepetitionWithSpacesNoMinNoSingleItemOpt, &ComputedStyle::setTestUnboundedRepetitionWithSpacesNoMinNoSingleItemOpt), // CSSPropertyID::TestUnboundedRepetitionWithSpacesNoMinNoSingleItemOpt
        new DiscreteWrapper(CSSPropertyID::TestUnboundedRepetitionWithSpacesWithMin, &ComputedStyle::testUnboundedRepetitionWithSpacesWithMin, &ComputedStyle::setTestUnboundedRepetitionWithSpacesWithMin), // CSSPropertyID::TestUnboundedRepetitionWithSpacesWithMin
        new DiscreteWrapper(CSSPropertyID::TestUnboundedRepetitionWithSpacesWithMinNoSingleItemOpt, &ComputedStyle::testUnboundedRepetitionWithSpacesWithMinNoSingleItemOpt, &ComputedStyle::setTestUnboundedRepetitionWithSpacesWithMinNoSingleItemOpt), // CSSPropertyID::TestUnboundedRepetitionWithSpacesWithMinNoSingleItemOpt
        new DiscreteWrapper(CSSPropertyID::TestUnboundedRepetitionWithSpacesWithMinSingleItemOpt, &ComputedStyle::testUnboundedRepetitionWithSpacesWithMinSingleItemOpt, &ComputedStyle::setTestUnboundedRepetitionWithSpacesWithMinSingleItemOpt), // CSSPropertyID::TestUnboundedRepetitionWithSpacesWithMinSingleItemOpt
        new DiscreteWrapper(CSSPropertyID::TestUrlWithModifiers, &ComputedStyle::testUrlWithModifiers, &ComputedStyle::setTestUrlWithModifiers), // CSSPropertyID::TestUrlWithModifiers
        new DiscreteWrapper(CSSPropertyID::TestUrlWithNoModifiers, &ComputedStyle::testUrlWithNoModifiers, &ComputedStyle::setTestUrlWithNoModifiers), // CSSPropertyID::TestUrlWithNoModifiers
        new DiscreteWrapper(CSSPropertyID::TestUsingSharedRule, &ComputedStyle::testUsingSharedRule, &ComputedStyle::setTestUsingSharedRule), // CSSPropertyID::TestUsingSharedRule
        new DiscreteWrapper(CSSPropertyID::TestUsingSharedRuleExported, &ComputedStyle::testUsingSharedRuleExported, &ComputedStyle::setTestUsingSharedRuleExported), // CSSPropertyID::TestUsingSharedRuleExported
        new DiscreteWrapper(CSSPropertyID::TestUsingSharedRuleWithOverrideFunction, &ComputedStyle::testUsingSharedRuleWithOverrideFunction, &ComputedStyle::setTestUsingSharedRuleWithOverrideFunction), // CSSPropertyID::TestUsingSharedRuleWithOverrideFunction
        new DiscreteWrapper(CSSPropertyID::TestSinkPriority, &ComputedStyle::testSinkPriority, &ComputedStyle::setTestSinkPriority), // CSSPropertyID::TestSinkPriority
        new DiscreteWrapper(CSSPropertyID::TestLogicalPropertyGroupPhysicalHorizontal, &ComputedStyle::testLogicalPropertyGroupPhysicalHorizontal, &ComputedStyle::setTestLogicalPropertyGroupPhysicalHorizontal), // CSSPropertyID::TestLogicalPropertyGroupPhysicalHorizontal
        new DiscreteWrapper(CSSPropertyID::TestLogicalPropertyGroupPhysicalVertical, &ComputedStyle::testLogicalPropertyGroupPhysicalVertical, &ComputedStyle::setTestLogicalPropertyGroupPhysicalVertical), // CSSPropertyID::TestLogicalPropertyGroupPhysicalVertical
        nullptr, // CSSPropertyID::TestLogicalPropertyGroupLogicalBlock - logical, handled via resolution to physical
        nullptr, // CSSPropertyID::TestLogicalPropertyGroupLogicalInline - logical, handled via resolution to physical
        nullptr, // CSSPropertyID::All - shorthand, will perform fix-up below
        nullptr, // CSSPropertyID::Font - shorthand, will perform fix-up below
        nullptr, // CSSPropertyID::TestShorthandOne - shorthand, will perform fix-up below
        nullptr, // CSSPropertyID::TestShorthandTwo - shorthand, will perform fix-up below
    }
{
    // Build animatable shorthand wrappers from longhand wrappers initialized above.

    m_wrappers[std::to_underlying(CSSPropertyID::All)] = makeShorthandWrapper(CSSPropertyID::All, m_wrappers);
    m_wrappers[std::to_underlying(CSSPropertyID::Font)] = makeShorthandWrapper(CSSPropertyID::Font, m_wrappers);
    m_wrappers[std::to_underlying(CSSPropertyID::TestShorthandOne)] = makeShorthandWrapper(CSSPropertyID::TestShorthandOne, m_wrappers);
    m_wrappers[std::to_underlying(CSSPropertyID::TestShorthandTwo)] = makeShorthandWrapper(CSSPropertyID::TestShorthandTwo, m_wrappers);
}

} // namespace WebCore
} // namespace Style
} // namespace Interpolation

