// This file is automatically generated from CSSProperties.json by the process-css-properties.py script. Do not edit it.

#include "config.h"
#include "StylePropertyShorthandFunctions.h"

#include "StylePropertyShorthand.h"

namespace WebCore {

StylePropertyShorthand allShorthand()
{
    static const CSSPropertyID allProperties[] = {
        CSSPropertyID::TestTopPriority,
        CSSPropertyID::TestHighPriority,
        CSSPropertyID::TestMediumPriority,
        CSSPropertyID::BackgroundCoordinatedValueListPropertyTestDiscrete,
        CSSPropertyID::BackgroundCoordinatedValueListPropertyTestTwo,
        CSSPropertyID::TestAnimationWrapper,
        CSSPropertyID::TestAnimationWrapperAccelerationAlways,
        CSSPropertyID::TestAnimationWrapperAccelerationThreadedOnly,
        CSSPropertyID::TestBoundedRepetitionWithCommas,
        CSSPropertyID::TestBoundedRepetitionWithCommasFixed,
        CSSPropertyID::TestBoundedRepetitionWithCommasNoSingleItemOpt,
        CSSPropertyID::TestBoundedRepetitionWithCommasSingleItemOpt,
        CSSPropertyID::TestBoundedRepetitionWithSpaces,
        CSSPropertyID::TestBoundedRepetitionWithSpacesFixed,
        CSSPropertyID::TestBoundedRepetitionWithSpacesNoSingleItemOpt,
        CSSPropertyID::TestBoundedRepetitionWithSpacesSingleItemOpt,
        CSSPropertyID::TestBoundedRepetitionWithSpacesWithType,
        CSSPropertyID::TestBoundedRepetitionWithSpacesWithTypeNoSingleItemOpt,
        CSSPropertyID::TestBoundedRepetitionWithSpacesWithTypeWithDefaultPrevious,
        CSSPropertyID::TestBoundedRepetitionWithSpacesWithTypeWithDefaultPreviousTwo,
        CSSPropertyID::TestColor,
        CSSPropertyID::TestColorAllowsTypesAbsolute,
        CSSPropertyID::TestColorPropertyWithVisitedLinkSupport,
        CSSPropertyID::TestCustomExtractor,
        CSSPropertyID::TestFunctionBoundedParameters,
        CSSPropertyID::TestFunctionFixedParameters,
        CSSPropertyID::TestFunctionNoParameters,
        CSSPropertyID::TestFunctionParametersMatchAllAnyOrder,
        CSSPropertyID::TestFunctionParametersMatchAllAnyOrderWithOptional,
        CSSPropertyID::TestFunctionParametersMatchAllOrdered,
        CSSPropertyID::TestFunctionParametersMatchAllOrderedWithOptional,
        CSSPropertyID::TestFunctionParametersMatchOneOrMoreAnyOrder,
        CSSPropertyID::TestFunctionSingleParameter,
        CSSPropertyID::TestFunctionSingleParameterMatchOne,
        CSSPropertyID::TestFunctionSingleParameterOptional,
        CSSPropertyID::TestFunctionUnboundedParametersNoMin,
        CSSPropertyID::TestFunctionUnboundedParametersWithMinimum,
        CSSPropertyID::TestImage,
        CSSPropertyID::TestImageNoImageSet,
        CSSPropertyID::TestKeyword,
        CSSPropertyID::TestKeywordWithAliasedTo,
        CSSPropertyID::TestMatchAllAnyOrder,
        CSSPropertyID::TestMatchAllAnyOrderWithCustomType,
        CSSPropertyID::TestMatchAllAnyOrderWithOptional,
        CSSPropertyID::TestMatchAllAnyOrderWithOptionalAndCustomType,
        CSSPropertyID::TestMatchAllAnyOrderWithOptionalAndMultipleRequiredAndCustomType,
        CSSPropertyID::TestMatchAllAnyOrderWithOptionalAndMultipleRequiredAndCustomTypeNoSingleItemOpt,
        CSSPropertyID::TestMatchAllAnyOrderWithOptionalAndMultipleRequiredAndPreserveOrderAndCustomType,
        CSSPropertyID::TestMatchAllAnyOrderWithOptionalAndMultipleRequiredAndPreserveOrderAndCustomTypeNoSingleItemOpt,
        CSSPropertyID::TestMatchAllAnyOrderWithOptionalAndPreserveOrderAndCustomType,
        CSSPropertyID::TestMatchAllAnyOrderWithOptionalNoSingleItemOpt,
        CSSPropertyID::TestMatchAllAnyOrderWithOptionalSingleItemOpt,
        CSSPropertyID::TestMatchAllAnyOrderWithOptionalWithPreserveOrder,
        CSSPropertyID::TestMatchAllAnyOrderWithOptionalWithPreserveOrderNoSingleItemOpt,
        CSSPropertyID::TestMatchAllAnyOrderWithPreserveOrder,
        CSSPropertyID::TestMatchAllAnyOrderWithPreserveOrderAndCustomType,
        CSSPropertyID::TestMatchAllAnyOrderWithPreserveOrderNoSingleItemOpt,
        CSSPropertyID::TestMatchAllOrdered,
        CSSPropertyID::TestMatchAllOrderedWithCustomType,
        CSSPropertyID::TestMatchAllOrderedWithOptional,
        CSSPropertyID::TestMatchAllOrderedWithOptionalAndCustomType,
        CSSPropertyID::TestMatchAllOrderedWithOptionalAndCustomTypeAndNoSingleItemOpt,
        CSSPropertyID::TestMatchAllOrderedWithOptionalAndMultipleRequired,
        CSSPropertyID::TestMatchAllOrderedWithOptionalAndMultipleRequiredAndCustomType,
        CSSPropertyID::TestMatchAllOrderedWithOptionalNoSingleItemOpt,
        CSSPropertyID::TestMatchAllOrderedWithOptionalSingleItemOpt,
        CSSPropertyID::TestMatchOne,
        CSSPropertyID::TestMatchOneOrMoreAnyOrder,
        CSSPropertyID::TestMatchOneOrMoreAnyOrderNoSingleItemOpt,
        CSSPropertyID::TestMatchOneOrMoreAnyOrderWithCustomType,
        CSSPropertyID::TestMatchOneOrMoreAnyOrderWithCustomTypeNoSingleItemOpt,
        CSSPropertyID::TestMatchOneOrMoreAnyOrderWithPreserveOrder,
        CSSPropertyID::TestMatchOneOrMoreAnyOrderWithPreserveOrderAndCustomType,
        CSSPropertyID::TestMatchOneOrMoreAnyOrderWithPreserveOrderAndCustomTypeNoSingleItemOpt,
        CSSPropertyID::TestMatchOneOrMoreAnyOrderWithPreserveOrderNoSingleItemOpt,
        CSSPropertyID::TestMatchOneWithGroupWithSettingsFlag,
        CSSPropertyID::TestMatchOneWithKeywordWithSettingsFlag,
        CSSPropertyID::TestMatchOneWithMultipleKeywords,
        CSSPropertyID::TestMatchOneWithReferenceWithSettingsFlag,
        CSSPropertyID::TestMatchOneWithSettingsFlag,
        CSSPropertyID::TestNumericValueRange,
        CSSPropertyID::TestProperty,
        CSSPropertyID::TestRenderStyleGetterNodeleteFalse,
        CSSPropertyID::TestRenderStyleHasExplicitlySetPolicyAllAuthorOrigin,
        CSSPropertyID::TestRenderStyleHasExplicitlySetPolicyAllBorderRadius,
        CSSPropertyID::TestRenderStyleHasExplicitlySetPolicyValueOnly,
        CSSPropertyID::TestRenderStyleStorageOneLevelEnum,
        CSSPropertyID::TestRenderStyleStorageOneLevelRaw,
        CSSPropertyID::TestRenderStyleStorageOneLevelReference,
        CSSPropertyID::TestRenderStyleStorageOneLevelValue,
        CSSPropertyID::TestRenderStyleStorageTwoLevelEnum,
        CSSPropertyID::TestRenderStyleStorageTwoLevelRaw,
        CSSPropertyID::TestRenderStyleStorageTwoLevelReference,
        CSSPropertyID::TestRenderStyleStorageTwoLevelValue,
        CSSPropertyID::TestSettingsOne,
        CSSPropertyID::TestUnboundedRepetitionWithCommasWithMin,
        CSSPropertyID::TestUnboundedRepetitionWithCommasWithMinNoSingleItemOpt,
        CSSPropertyID::TestUnboundedRepetitionWithCommasWithMinSingleItemOpt,
        CSSPropertyID::TestUnboundedRepetitionWithSpacesNoMin,
        CSSPropertyID::TestUnboundedRepetitionWithSpacesNoMinNoSingleItemOpt,
        CSSPropertyID::TestUnboundedRepetitionWithSpacesWithMin,
        CSSPropertyID::TestUnboundedRepetitionWithSpacesWithMinNoSingleItemOpt,
        CSSPropertyID::TestUnboundedRepetitionWithSpacesWithMinSingleItemOpt,
        CSSPropertyID::TestUrlWithModifiers,
        CSSPropertyID::TestUrlWithNoModifiers,
        CSSPropertyID::TestUsingSharedRule,
        CSSPropertyID::TestUsingSharedRuleExported,
        CSSPropertyID::TestUsingSharedRuleWithOverrideFunction,
        CSSPropertyID::TestSinkPriority,
        CSSPropertyID::TestLogicalPropertyGroupPhysicalHorizontal,
        CSSPropertyID::TestLogicalPropertyGroupPhysicalVertical,
        CSSPropertyID::TestLogicalPropertyGroupLogicalBlock,
        CSSPropertyID::TestLogicalPropertyGroupLogicalInline,
    };
    return StylePropertyShorthand(CSSPropertyID::All, std::span { allProperties });
}

StylePropertyShorthand fontShorthand()
{
    static const CSSPropertyID fontProperties[] = {
        CSSPropertyID::TestSinkPriority,
        CSSPropertyID::TestHighPriority,
    };
    return StylePropertyShorthand(CSSPropertyID::Font, std::span { fontProperties });
}

StylePropertyShorthand testShorthandOneShorthand()
{
    static const CSSPropertyID testShorthandOneProperties[] = {
        CSSPropertyID::TestLogicalPropertyGroupPhysicalHorizontal,
        CSSPropertyID::TestLogicalPropertyGroupPhysicalVertical,
    };
    return StylePropertyShorthand(CSSPropertyID::TestShorthandOne, std::span { testShorthandOneProperties });
}

StylePropertyShorthand testShorthandTwoShorthand()
{
    static const CSSPropertyID testShorthandTwoProperties[] = {
        CSSPropertyID::TestLogicalPropertyGroupLogicalBlock,
        CSSPropertyID::TestLogicalPropertyGroupLogicalInline,
    };
    return StylePropertyShorthand(CSSPropertyID::TestShorthandTwo, std::span { testShorthandTwoProperties });
}

StylePropertyShorthand shorthandForProperty(CSSPropertyID id)
{
    switch (id) {
    case CSSPropertyID::All:
        return allShorthand();
    case CSSPropertyID::Font:
        return fontShorthand();
    case CSSPropertyID::TestShorthandOne:
        return testShorthandOneShorthand();
    case CSSPropertyID::TestShorthandTwo:
        return testShorthandTwoShorthand();
    default:
        return { };
    }
}

StylePropertyShorthandVector matchingShorthandsForLonghand(CSSPropertyID id)
{
    switch (id) {
    case CSSPropertyID::TestHighPriority:
    case CSSPropertyID::TestSinkPriority:
        return StylePropertyShorthandVector{allShorthand(), fontShorthand()};
    case CSSPropertyID::TestLogicalPropertyGroupPhysicalHorizontal:
    case CSSPropertyID::TestLogicalPropertyGroupPhysicalVertical:
        return StylePropertyShorthandVector{allShorthand(), testShorthandOneShorthand()};
    case CSSPropertyID::TestLogicalPropertyGroupLogicalBlock:
    case CSSPropertyID::TestLogicalPropertyGroupLogicalInline:
        return StylePropertyShorthandVector{allShorthand(), testShorthandTwoShorthand()};
    case CSSPropertyID::BackgroundCoordinatedValueListPropertyTestDiscrete:
    case CSSPropertyID::BackgroundCoordinatedValueListPropertyTestTwo:
    case CSSPropertyID::TestAnimationWrapper:
    case CSSPropertyID::TestAnimationWrapperAccelerationAlways:
    case CSSPropertyID::TestAnimationWrapperAccelerationThreadedOnly:
    case CSSPropertyID::TestBoundedRepetitionWithCommas:
    case CSSPropertyID::TestBoundedRepetitionWithCommasFixed:
    case CSSPropertyID::TestBoundedRepetitionWithCommasNoSingleItemOpt:
    case CSSPropertyID::TestBoundedRepetitionWithCommasSingleItemOpt:
    case CSSPropertyID::TestBoundedRepetitionWithSpaces:
    case CSSPropertyID::TestBoundedRepetitionWithSpacesFixed:
    case CSSPropertyID::TestBoundedRepetitionWithSpacesNoSingleItemOpt:
    case CSSPropertyID::TestBoundedRepetitionWithSpacesSingleItemOpt:
    case CSSPropertyID::TestBoundedRepetitionWithSpacesWithType:
    case CSSPropertyID::TestBoundedRepetitionWithSpacesWithTypeNoSingleItemOpt:
    case CSSPropertyID::TestBoundedRepetitionWithSpacesWithTypeWithDefaultPrevious:
    case CSSPropertyID::TestBoundedRepetitionWithSpacesWithTypeWithDefaultPreviousTwo:
    case CSSPropertyID::TestColor:
    case CSSPropertyID::TestColorAllowsTypesAbsolute:
    case CSSPropertyID::TestColorPropertyWithVisitedLinkSupport:
    case CSSPropertyID::TestCustomExtractor:
    case CSSPropertyID::TestFunctionBoundedParameters:
    case CSSPropertyID::TestFunctionFixedParameters:
    case CSSPropertyID::TestFunctionNoParameters:
    case CSSPropertyID::TestFunctionParametersMatchAllAnyOrder:
    case CSSPropertyID::TestFunctionParametersMatchAllAnyOrderWithOptional:
    case CSSPropertyID::TestFunctionParametersMatchAllOrdered:
    case CSSPropertyID::TestFunctionParametersMatchAllOrderedWithOptional:
    case CSSPropertyID::TestFunctionParametersMatchOneOrMoreAnyOrder:
    case CSSPropertyID::TestFunctionSingleParameter:
    case CSSPropertyID::TestFunctionSingleParameterMatchOne:
    case CSSPropertyID::TestFunctionSingleParameterOptional:
    case CSSPropertyID::TestFunctionUnboundedParametersNoMin:
    case CSSPropertyID::TestFunctionUnboundedParametersWithMinimum:
    case CSSPropertyID::TestImage:
    case CSSPropertyID::TestImageNoImageSet:
    case CSSPropertyID::TestKeyword:
    case CSSPropertyID::TestKeywordWithAliasedTo:
    case CSSPropertyID::TestMatchAllAnyOrder:
    case CSSPropertyID::TestMatchAllAnyOrderWithCustomType:
    case CSSPropertyID::TestMatchAllAnyOrderWithOptional:
    case CSSPropertyID::TestMatchAllAnyOrderWithOptionalAndCustomType:
    case CSSPropertyID::TestMatchAllAnyOrderWithOptionalAndMultipleRequiredAndCustomType:
    case CSSPropertyID::TestMatchAllAnyOrderWithOptionalAndMultipleRequiredAndCustomTypeNoSingleItemOpt:
    case CSSPropertyID::TestMatchAllAnyOrderWithOptionalAndMultipleRequiredAndPreserveOrderAndCustomType:
    case CSSPropertyID::TestMatchAllAnyOrderWithOptionalAndMultipleRequiredAndPreserveOrderAndCustomTypeNoSingleItemOpt:
    case CSSPropertyID::TestMatchAllAnyOrderWithOptionalAndPreserveOrderAndCustomType:
    case CSSPropertyID::TestMatchAllAnyOrderWithOptionalNoSingleItemOpt:
    case CSSPropertyID::TestMatchAllAnyOrderWithOptionalSingleItemOpt:
    case CSSPropertyID::TestMatchAllAnyOrderWithOptionalWithPreserveOrder:
    case CSSPropertyID::TestMatchAllAnyOrderWithOptionalWithPreserveOrderNoSingleItemOpt:
    case CSSPropertyID::TestMatchAllAnyOrderWithPreserveOrder:
    case CSSPropertyID::TestMatchAllAnyOrderWithPreserveOrderAndCustomType:
    case CSSPropertyID::TestMatchAllAnyOrderWithPreserveOrderNoSingleItemOpt:
    case CSSPropertyID::TestMatchAllOrdered:
    case CSSPropertyID::TestMatchAllOrderedWithCustomType:
    case CSSPropertyID::TestMatchAllOrderedWithOptional:
    case CSSPropertyID::TestMatchAllOrderedWithOptionalAndCustomType:
    case CSSPropertyID::TestMatchAllOrderedWithOptionalAndCustomTypeAndNoSingleItemOpt:
    case CSSPropertyID::TestMatchAllOrderedWithOptionalAndMultipleRequired:
    case CSSPropertyID::TestMatchAllOrderedWithOptionalAndMultipleRequiredAndCustomType:
    case CSSPropertyID::TestMatchAllOrderedWithOptionalNoSingleItemOpt:
    case CSSPropertyID::TestMatchAllOrderedWithOptionalSingleItemOpt:
    case CSSPropertyID::TestMatchOne:
    case CSSPropertyID::TestMatchOneOrMoreAnyOrder:
    case CSSPropertyID::TestMatchOneOrMoreAnyOrderNoSingleItemOpt:
    case CSSPropertyID::TestMatchOneOrMoreAnyOrderWithCustomType:
    case CSSPropertyID::TestMatchOneOrMoreAnyOrderWithCustomTypeNoSingleItemOpt:
    case CSSPropertyID::TestMatchOneOrMoreAnyOrderWithPreserveOrder:
    case CSSPropertyID::TestMatchOneOrMoreAnyOrderWithPreserveOrderAndCustomType:
    case CSSPropertyID::TestMatchOneOrMoreAnyOrderWithPreserveOrderAndCustomTypeNoSingleItemOpt:
    case CSSPropertyID::TestMatchOneOrMoreAnyOrderWithPreserveOrderNoSingleItemOpt:
    case CSSPropertyID::TestMatchOneWithGroupWithSettingsFlag:
    case CSSPropertyID::TestMatchOneWithKeywordWithSettingsFlag:
    case CSSPropertyID::TestMatchOneWithMultipleKeywords:
    case CSSPropertyID::TestMatchOneWithReferenceWithSettingsFlag:
    case CSSPropertyID::TestMatchOneWithSettingsFlag:
    case CSSPropertyID::TestMediumPriority:
    case CSSPropertyID::TestNumericValueRange:
    case CSSPropertyID::TestProperty:
    case CSSPropertyID::TestRenderStyleGetterNodeleteFalse:
    case CSSPropertyID::TestRenderStyleHasExplicitlySetPolicyAllAuthorOrigin:
    case CSSPropertyID::TestRenderStyleHasExplicitlySetPolicyAllBorderRadius:
    case CSSPropertyID::TestRenderStyleHasExplicitlySetPolicyValueOnly:
    case CSSPropertyID::TestRenderStyleStorageOneLevelEnum:
    case CSSPropertyID::TestRenderStyleStorageOneLevelRaw:
    case CSSPropertyID::TestRenderStyleStorageOneLevelReference:
    case CSSPropertyID::TestRenderStyleStorageOneLevelValue:
    case CSSPropertyID::TestRenderStyleStorageTwoLevelEnum:
    case CSSPropertyID::TestRenderStyleStorageTwoLevelRaw:
    case CSSPropertyID::TestRenderStyleStorageTwoLevelReference:
    case CSSPropertyID::TestRenderStyleStorageTwoLevelValue:
    case CSSPropertyID::TestSettingsOne:
    case CSSPropertyID::TestTopPriority:
    case CSSPropertyID::TestUnboundedRepetitionWithCommasWithMin:
    case CSSPropertyID::TestUnboundedRepetitionWithCommasWithMinNoSingleItemOpt:
    case CSSPropertyID::TestUnboundedRepetitionWithCommasWithMinSingleItemOpt:
    case CSSPropertyID::TestUnboundedRepetitionWithSpacesNoMin:
    case CSSPropertyID::TestUnboundedRepetitionWithSpacesNoMinNoSingleItemOpt:
    case CSSPropertyID::TestUnboundedRepetitionWithSpacesWithMin:
    case CSSPropertyID::TestUnboundedRepetitionWithSpacesWithMinNoSingleItemOpt:
    case CSSPropertyID::TestUnboundedRepetitionWithSpacesWithMinSingleItemOpt:
    case CSSPropertyID::TestUrlWithModifiers:
    case CSSPropertyID::TestUrlWithNoModifiers:
    case CSSPropertyID::TestUsingSharedRule:
    case CSSPropertyID::TestUsingSharedRuleExported:
    case CSSPropertyID::TestUsingSharedRuleWithOverrideFunction:
        return StylePropertyShorthandVector{allShorthand()};
    default:
        return { };
    }
}

} // namespace WebCore

