// This file is automatically generated from CSSProperties.json by the process-css-properties.py script. Do not edit it.

#include "config.h"
#include "StyleExtractorGenerated.h"

#include "CSSProperty.h"
#include "ColorSerialization.h"
#include "StyleComputedStyle.h"
#include "StyleExtractorCustom.h"
#include "StyleExtractorState.h"
#include "StyleKeyword+Mappings.h"
#include "StylePropertyShorthand.h"

namespace WebCore {
namespace Style {

class ExtractorFunctions {
public:
    static RefPtr<CSSValue> extractBackgroundCoordinatedValueListPropertyTestDiscrete(ExtractorState& extractorState)
    {
        auto mapper = [](auto& extractorState, const auto& value, const std::optional<BackgroundLayers::value_type>&, const auto&) -> Ref<CSSValue> {
            return createCSSValue(extractorState.pool, extractorState.style, value);
        };
        return extractCoordinatedValueListValue<CSSPropertyID::BackgroundCoordinatedValueListPropertyTestDiscrete>(extractorState, extractorState.style.backgroundLayers(), mapper);
    }
    static void extractBackgroundCoordinatedValueListPropertyTestDiscreteSerialization(ExtractorState& extractorState, StringBuilder& builder, const CSS::SerializationContext& context)
    {
        auto mapper = [](auto& extractorState, auto& builder, const auto& context, const auto& value, const std::optional<BackgroundLayers::value_type>&, const auto&) {
            serializationForCSS(builder, context, extractorState.style, value);
        };
        extractCoordinatedValueListSerialization<CSSPropertyID::BackgroundCoordinatedValueListPropertyTestDiscrete>(extractorState, builder, context, extractorState.style.backgroundLayers(), mapper);
    }
    static RefPtr<CSSValue> extractBackgroundCoordinatedValueListPropertyTestTwo(ExtractorState& extractorState)
    {
        auto mapper = [](auto& extractorState, const auto& value, const std::optional<BackgroundLayers::value_type>&, const auto&) -> Ref<CSSValue> {
            return createCSSValue(extractorState.pool, extractorState.style, value);
        };
        return extractCoordinatedValueListValue<CSSPropertyID::BackgroundCoordinatedValueListPropertyTestTwo>(extractorState, extractorState.style.backgroundLayers(), mapper);
    }
    static void extractBackgroundCoordinatedValueListPropertyTestTwoSerialization(ExtractorState& extractorState, StringBuilder& builder, const CSS::SerializationContext& context)
    {
        auto mapper = [](auto& extractorState, auto& builder, const auto& context, const auto& value, const std::optional<BackgroundLayers::value_type>&, const auto&) {
            serializationForCSS(builder, context, extractorState.style, value);
        };
        extractCoordinatedValueListSerialization<CSSPropertyID::BackgroundCoordinatedValueListPropertyTestTwo>(extractorState, builder, context, extractorState.style.backgroundLayers(), mapper);
    }
    static RefPtr<CSSValue> extractTestAnimationWrapper(ExtractorState& extractorState)
    {
        return createCSSValue(extractorState.pool, extractorState.style, extractorState.style.testAnimationWrapper());
    }
    static void extractTestAnimationWrapperSerialization(ExtractorState& extractorState, StringBuilder& builder, const CSS::SerializationContext& context)
    {
        serializationForCSS(builder, context, extractorState.style, extractorState.style.testAnimationWrapper());
    }
    static RefPtr<CSSValue> extractTestAnimationWrapperAccelerationAlways(ExtractorState& extractorState)
    {
        return createCSSValue(extractorState.pool, extractorState.style, extractorState.style.testAnimationWrapperAccelerationAlways());
    }
    static void extractTestAnimationWrapperAccelerationAlwaysSerialization(ExtractorState& extractorState, StringBuilder& builder, const CSS::SerializationContext& context)
    {
        serializationForCSS(builder, context, extractorState.style, extractorState.style.testAnimationWrapperAccelerationAlways());
    }
    static RefPtr<CSSValue> extractTestAnimationWrapperAccelerationThreadedOnly(ExtractorState& extractorState)
    {
        return createCSSValue(extractorState.pool, extractorState.style, extractorState.style.testAnimationWrapperAccelerationThreadedOnly());
    }
    static void extractTestAnimationWrapperAccelerationThreadedOnlySerialization(ExtractorState& extractorState, StringBuilder& builder, const CSS::SerializationContext& context)
    {
        serializationForCSS(builder, context, extractorState.style, extractorState.style.testAnimationWrapperAccelerationThreadedOnly());
    }
    static RefPtr<CSSValue> extractTestColor(ExtractorState& extractorState)
    {
        return createCSSValue(extractorState.pool, extractorState.style, extractorState.style.testColor());
    }
    static void extractTestColorSerialization(ExtractorState& extractorState, StringBuilder& builder, const CSS::SerializationContext& context)
    {
        serializationForCSS(builder, context, extractorState.style, extractorState.style.testColor());
    }
    static RefPtr<CSSValue> extractTestColorAllowsTypesAbsolute(ExtractorState& extractorState)
    {
        return createCSSValue(extractorState.pool, extractorState.style, extractorState.style.testColorAllowsTypesAbsolute());
    }
    static void extractTestColorAllowsTypesAbsoluteSerialization(ExtractorState& extractorState, StringBuilder& builder, const CSS::SerializationContext& context)
    {
        serializationForCSS(builder, context, extractorState.style, extractorState.style.testColorAllowsTypesAbsolute());
    }
    static RefPtr<CSSValue> extractTestColorPropertyWithVisitedLinkSupport(ExtractorState& extractorState)
    {
        if (extractorState.allowVisitedStyle) {
            return extractorState.pool.createColorValue(extractorState.style.visitedDependentTestColorPropertyWithVisitedLinkSupport());
        }
        return createCSSValue(extractorState.pool, extractorState.style, extractorState.style.testColorPropertyWithVisitedLinkSupport());
    }
    static void extractTestColorPropertyWithVisitedLinkSupportSerialization(ExtractorState& extractorState, StringBuilder& builder, const CSS::SerializationContext& context)
    {
        if (extractorState.allowVisitedStyle) {
            builder.append(WebCore::serializationForCSS(extractorState.style.visitedDependentTestColorPropertyWithVisitedLinkSupport()));
            return;
        }
        serializationForCSS(builder, context, extractorState.style, extractorState.style.testColorPropertyWithVisitedLinkSupport());
    }
    static RefPtr<CSSValue> extractTestRenderStyleGetterNodeleteFalse(ExtractorState& extractorState)
    {
        return createCSSValue(extractorState.pool, extractorState.style, extractorState.style.testRenderStyleGetterNodeleteFalse());
    }
    static void extractTestRenderStyleGetterNodeleteFalseSerialization(ExtractorState& extractorState, StringBuilder& builder, const CSS::SerializationContext& context)
    {
        serializationForCSS(builder, context, extractorState.style, extractorState.style.testRenderStyleGetterNodeleteFalse());
    }
    static RefPtr<CSSValue> extractTestRenderStyleHasExplicitlySetPolicyAllAuthorOrigin(ExtractorState& extractorState)
    {
        return createCSSValue(extractorState.pool, extractorState.style, extractorState.style.testRenderStyleHasExplicitlySetPolicyAllAuthorOrigin());
    }
    static void extractTestRenderStyleHasExplicitlySetPolicyAllAuthorOriginSerialization(ExtractorState& extractorState, StringBuilder& builder, const CSS::SerializationContext& context)
    {
        serializationForCSS(builder, context, extractorState.style, extractorState.style.testRenderStyleHasExplicitlySetPolicyAllAuthorOrigin());
    }
    static RefPtr<CSSValue> extractTestRenderStyleHasExplicitlySetPolicyAllBorderRadius(ExtractorState& extractorState)
    {
        return createCSSValue(extractorState.pool, extractorState.style, extractorState.style.testRenderStyleHasExplicitlySetPolicyAllBorderRadius());
    }
    static void extractTestRenderStyleHasExplicitlySetPolicyAllBorderRadiusSerialization(ExtractorState& extractorState, StringBuilder& builder, const CSS::SerializationContext& context)
    {
        serializationForCSS(builder, context, extractorState.style, extractorState.style.testRenderStyleHasExplicitlySetPolicyAllBorderRadius());
    }
    static RefPtr<CSSValue> extractTestRenderStyleHasExplicitlySetPolicyValueOnly(ExtractorState& extractorState)
    {
        return createCSSValue(extractorState.pool, extractorState.style, extractorState.style.testRenderStyleHasExplicitlySetPolicyValueOnly());
    }
    static void extractTestRenderStyleHasExplicitlySetPolicyValueOnlySerialization(ExtractorState& extractorState, StringBuilder& builder, const CSS::SerializationContext& context)
    {
        serializationForCSS(builder, context, extractorState.style, extractorState.style.testRenderStyleHasExplicitlySetPolicyValueOnly());
    }
    static RefPtr<CSSValue> extractTestRenderStyleStorageOneLevelEnum(ExtractorState& extractorState)
    {
        return createCSSValue(extractorState.pool, extractorState.style, extractorState.style.testRenderStyleStorageOneLevelEnum());
    }
    static void extractTestRenderStyleStorageOneLevelEnumSerialization(ExtractorState& extractorState, StringBuilder& builder, const CSS::SerializationContext& context)
    {
        serializationForCSS(builder, context, extractorState.style, extractorState.style.testRenderStyleStorageOneLevelEnum());
    }
    static RefPtr<CSSValue> extractTestRenderStyleStorageOneLevelRaw(ExtractorState& extractorState)
    {
        return createCSSValue(extractorState.pool, extractorState.style, extractorState.style.testRenderStyleStorageOneLevelRaw());
    }
    static void extractTestRenderStyleStorageOneLevelRawSerialization(ExtractorState& extractorState, StringBuilder& builder, const CSS::SerializationContext& context)
    {
        serializationForCSS(builder, context, extractorState.style, extractorState.style.testRenderStyleStorageOneLevelRaw());
    }
    static RefPtr<CSSValue> extractTestRenderStyleStorageOneLevelReference(ExtractorState& extractorState)
    {
        return createCSSValue(extractorState.pool, extractorState.style, extractorState.style.testRenderStyleStorageOneLevelReference());
    }
    static void extractTestRenderStyleStorageOneLevelReferenceSerialization(ExtractorState& extractorState, StringBuilder& builder, const CSS::SerializationContext& context)
    {
        serializationForCSS(builder, context, extractorState.style, extractorState.style.testRenderStyleStorageOneLevelReference());
    }
    static RefPtr<CSSValue> extractTestRenderStyleStorageOneLevelValue(ExtractorState& extractorState)
    {
        return createCSSValue(extractorState.pool, extractorState.style, extractorState.style.testRenderStyleStorageOneLevelValue());
    }
    static void extractTestRenderStyleStorageOneLevelValueSerialization(ExtractorState& extractorState, StringBuilder& builder, const CSS::SerializationContext& context)
    {
        serializationForCSS(builder, context, extractorState.style, extractorState.style.testRenderStyleStorageOneLevelValue());
    }
    static RefPtr<CSSValue> extractTestRenderStyleStorageTwoLevelEnum(ExtractorState& extractorState)
    {
        return createCSSValue(extractorState.pool, extractorState.style, extractorState.style.testRenderStyleStorageTwoLevelEnum());
    }
    static void extractTestRenderStyleStorageTwoLevelEnumSerialization(ExtractorState& extractorState, StringBuilder& builder, const CSS::SerializationContext& context)
    {
        serializationForCSS(builder, context, extractorState.style, extractorState.style.testRenderStyleStorageTwoLevelEnum());
    }
    static RefPtr<CSSValue> extractTestRenderStyleStorageTwoLevelRaw(ExtractorState& extractorState)
    {
        return createCSSValue(extractorState.pool, extractorState.style, extractorState.style.testRenderStyleStorageTwoLevelRaw());
    }
    static void extractTestRenderStyleStorageTwoLevelRawSerialization(ExtractorState& extractorState, StringBuilder& builder, const CSS::SerializationContext& context)
    {
        serializationForCSS(builder, context, extractorState.style, extractorState.style.testRenderStyleStorageTwoLevelRaw());
    }
    static RefPtr<CSSValue> extractTestRenderStyleStorageTwoLevelReference(ExtractorState& extractorState)
    {
        return createCSSValue(extractorState.pool, extractorState.style, extractorState.style.testRenderStyleStorageTwoLevelReference());
    }
    static void extractTestRenderStyleStorageTwoLevelReferenceSerialization(ExtractorState& extractorState, StringBuilder& builder, const CSS::SerializationContext& context)
    {
        serializationForCSS(builder, context, extractorState.style, extractorState.style.testRenderStyleStorageTwoLevelReference());
    }
    static RefPtr<CSSValue> extractTestRenderStyleStorageTwoLevelValue(ExtractorState& extractorState)
    {
        return createCSSValue(extractorState.pool, extractorState.style, extractorState.style.testRenderStyleStorageTwoLevelValue());
    }
    static void extractTestRenderStyleStorageTwoLevelValueSerialization(ExtractorState& extractorState, StringBuilder& builder, const CSS::SerializationContext& context)
    {
        serializationForCSS(builder, context, extractorState.style, extractorState.style.testRenderStyleStorageTwoLevelValue());
    }
    static RefPtr<CSSValue> extractTestSettingsOne(ExtractorState& extractorState)
    {
        return createCSSValue(extractorState.pool, extractorState.style, extractorState.style.testSettingsOne());
    }
    static void extractTestSettingsOneSerialization(ExtractorState& extractorState, StringBuilder& builder, const CSS::SerializationContext& context)
    {
        serializationForCSS(builder, context, extractorState.style, extractorState.style.testSettingsOne());
    }
    static RefPtr<CSSValue> extractTestLogicalPropertyGroupPhysicalVertical(ExtractorState& extractorState)
    {
        return createCSSValue(extractorState.pool, extractorState.style, extractorState.style.testLogicalPropertyGroupPhysicalVertical());
    }
    static void extractTestLogicalPropertyGroupPhysicalVerticalSerialization(ExtractorState& extractorState, StringBuilder& builder, const CSS::SerializationContext& context)
    {
        serializationForCSS(builder, context, extractorState.style, extractorState.style.testLogicalPropertyGroupPhysicalVertical());
    }
};

RefPtr<CSSValue> ExtractorGenerated::extractValue(ExtractorState& extractorState, CSSPropertyID id)
{
    switch (id) {
    case CSSPropertyID::Invalid:
        break;
    case CSSPropertyID::Custom:
        ASSERT_NOT_REACHED();
        break;
    case CSSPropertyID::TestTopPriority:
        // Skipped - Not computable
        return nullptr;
    case CSSPropertyID::TestHighPriority:
        // Skipped - Not computable
        return nullptr;
    case CSSPropertyID::TestMediumPriority:
        // Skipped - Not computable
        return nullptr;
    case CSSPropertyID::BackgroundCoordinatedValueListPropertyTestDiscrete:
        return ExtractorFunctions::extractBackgroundCoordinatedValueListPropertyTestDiscrete(extractorState);
    case CSSPropertyID::BackgroundCoordinatedValueListPropertyTestTwo:
        return ExtractorFunctions::extractBackgroundCoordinatedValueListPropertyTestTwo(extractorState);
    case CSSPropertyID::FirstTestDescriptorForFirstDescriptor:
        // Skipped - Descriptor-only property
        return nullptr;
    case CSSPropertyID::FirstTestDescriptorForSecondDescriptor:
        // Skipped - Descriptor-only property
        return nullptr;
    case CSSPropertyID::TestAnimationWrapper:
        return ExtractorFunctions::extractTestAnimationWrapper(extractorState);
    case CSSPropertyID::TestAnimationWrapperAccelerationAlways:
        return ExtractorFunctions::extractTestAnimationWrapperAccelerationAlways(extractorState);
    case CSSPropertyID::TestAnimationWrapperAccelerationThreadedOnly:
        return ExtractorFunctions::extractTestAnimationWrapperAccelerationThreadedOnly(extractorState);
    case CSSPropertyID::TestBoundedRepetitionWithCommas:
        // Skipped - Not computable
        return nullptr;
    case CSSPropertyID::TestBoundedRepetitionWithCommasFixed:
        // Skipped - Not computable
        return nullptr;
    case CSSPropertyID::TestBoundedRepetitionWithCommasNoSingleItemOpt:
        // Skipped - Not computable
        return nullptr;
    case CSSPropertyID::TestBoundedRepetitionWithCommasSingleItemOpt:
        // Skipped - Not computable
        return nullptr;
    case CSSPropertyID::TestBoundedRepetitionWithSpaces:
        // Skipped - Not computable
        return nullptr;
    case CSSPropertyID::TestBoundedRepetitionWithSpacesFixed:
        // Skipped - Not computable
        return nullptr;
    case CSSPropertyID::TestBoundedRepetitionWithSpacesNoSingleItemOpt:
        // Skipped - Not computable
        return nullptr;
    case CSSPropertyID::TestBoundedRepetitionWithSpacesSingleItemOpt:
        // Skipped - Not computable
        return nullptr;
    case CSSPropertyID::TestBoundedRepetitionWithSpacesWithType:
        // Skipped - Not computable
        return nullptr;
    case CSSPropertyID::TestBoundedRepetitionWithSpacesWithTypeNoSingleItemOpt:
        // Skipped - Not computable
        return nullptr;
    case CSSPropertyID::TestBoundedRepetitionWithSpacesWithTypeWithDefaultPrevious:
        // Skipped - Not computable
        return nullptr;
    case CSSPropertyID::TestBoundedRepetitionWithSpacesWithTypeWithDefaultPreviousTwo:
        // Skipped - Not computable
        return nullptr;
    case CSSPropertyID::TestColor:
        return ExtractorFunctions::extractTestColor(extractorState);
    case CSSPropertyID::TestColorAllowsTypesAbsolute:
        return ExtractorFunctions::extractTestColorAllowsTypesAbsolute(extractorState);
    case CSSPropertyID::TestColorPropertyWithVisitedLinkSupport:
        return ExtractorFunctions::extractTestColorPropertyWithVisitedLinkSupport(extractorState);
    case CSSPropertyID::TestCustomExtractor:
        return ExtractorCustom::extractTestCustomExtractor(extractorState);
    case CSSPropertyID::TestFunctionBoundedParameters:
        // Skipped - Not computable
        return nullptr;
    case CSSPropertyID::TestFunctionFixedParameters:
        // Skipped - Not computable
        return nullptr;
    case CSSPropertyID::TestFunctionNoParameters:
        // Skipped - Not computable
        return nullptr;
    case CSSPropertyID::TestFunctionParametersMatchAllAnyOrder:
        // Skipped - Not computable
        return nullptr;
    case CSSPropertyID::TestFunctionParametersMatchAllAnyOrderWithOptional:
        // Skipped - Not computable
        return nullptr;
    case CSSPropertyID::TestFunctionParametersMatchAllOrdered:
        // Skipped - Not computable
        return nullptr;
    case CSSPropertyID::TestFunctionParametersMatchAllOrderedWithOptional:
        // Skipped - Not computable
        return nullptr;
    case CSSPropertyID::TestFunctionParametersMatchOneOrMoreAnyOrder:
        // Skipped - Not computable
        return nullptr;
    case CSSPropertyID::TestFunctionSingleParameter:
        // Skipped - Not computable
        return nullptr;
    case CSSPropertyID::TestFunctionSingleParameterMatchOne:
        // Skipped - Not computable
        return nullptr;
    case CSSPropertyID::TestFunctionSingleParameterOptional:
        // Skipped - Not computable
        return nullptr;
    case CSSPropertyID::TestFunctionUnboundedParametersNoMin:
        // Skipped - Not computable
        return nullptr;
    case CSSPropertyID::TestFunctionUnboundedParametersWithMinimum:
        // Skipped - Not computable
        return nullptr;
    case CSSPropertyID::TestImage:
        // Skipped - Not computable
        return nullptr;
    case CSSPropertyID::TestImageNoImageSet:
        // Skipped - Not computable
        return nullptr;
    case CSSPropertyID::TestKeyword:
        // Skipped - Not computable
        return nullptr;
    case CSSPropertyID::TestKeywordWithAliasedTo:
        // Skipped - Not computable
        return nullptr;
    case CSSPropertyID::TestMatchAllAnyOrder:
        // Skipped - Not computable
        return nullptr;
    case CSSPropertyID::TestMatchAllAnyOrderWithCustomType:
        // Skipped - Not computable
        return nullptr;
    case CSSPropertyID::TestMatchAllAnyOrderWithOptional:
        // Skipped - Not computable
        return nullptr;
    case CSSPropertyID::TestMatchAllAnyOrderWithOptionalAndCustomType:
        // Skipped - Not computable
        return nullptr;
    case CSSPropertyID::TestMatchAllAnyOrderWithOptionalAndMultipleRequiredAndCustomType:
        // Skipped - Not computable
        return nullptr;
    case CSSPropertyID::TestMatchAllAnyOrderWithOptionalAndMultipleRequiredAndCustomTypeNoSingleItemOpt:
        // Skipped - Not computable
        return nullptr;
    case CSSPropertyID::TestMatchAllAnyOrderWithOptionalAndMultipleRequiredAndPreserveOrderAndCustomType:
        // Skipped - Not computable
        return nullptr;
    case CSSPropertyID::TestMatchAllAnyOrderWithOptionalAndMultipleRequiredAndPreserveOrderAndCustomTypeNoSingleItemOpt:
        // Skipped - Not computable
        return nullptr;
    case CSSPropertyID::TestMatchAllAnyOrderWithOptionalAndPreserveOrderAndCustomType:
        // Skipped - Not computable
        return nullptr;
    case CSSPropertyID::TestMatchAllAnyOrderWithOptionalNoSingleItemOpt:
        // Skipped - Not computable
        return nullptr;
    case CSSPropertyID::TestMatchAllAnyOrderWithOptionalSingleItemOpt:
        // Skipped - Not computable
        return nullptr;
    case CSSPropertyID::TestMatchAllAnyOrderWithOptionalWithPreserveOrder:
        // Skipped - Not computable
        return nullptr;
    case CSSPropertyID::TestMatchAllAnyOrderWithOptionalWithPreserveOrderNoSingleItemOpt:
        // Skipped - Not computable
        return nullptr;
    case CSSPropertyID::TestMatchAllAnyOrderWithPreserveOrder:
        // Skipped - Not computable
        return nullptr;
    case CSSPropertyID::TestMatchAllAnyOrderWithPreserveOrderAndCustomType:
        // Skipped - Not computable
        return nullptr;
    case CSSPropertyID::TestMatchAllAnyOrderWithPreserveOrderNoSingleItemOpt:
        // Skipped - Not computable
        return nullptr;
    case CSSPropertyID::TestMatchAllOrdered:
        // Skipped - Not computable
        return nullptr;
    case CSSPropertyID::TestMatchAllOrderedWithCustomType:
        // Skipped - Not computable
        return nullptr;
    case CSSPropertyID::TestMatchAllOrderedWithOptional:
        // Skipped - Not computable
        return nullptr;
    case CSSPropertyID::TestMatchAllOrderedWithOptionalAndCustomType:
        // Skipped - Not computable
        return nullptr;
    case CSSPropertyID::TestMatchAllOrderedWithOptionalAndCustomTypeAndNoSingleItemOpt:
        // Skipped - Not computable
        return nullptr;
    case CSSPropertyID::TestMatchAllOrderedWithOptionalAndMultipleRequired:
        // Skipped - Not computable
        return nullptr;
    case CSSPropertyID::TestMatchAllOrderedWithOptionalAndMultipleRequiredAndCustomType:
        // Skipped - Not computable
        return nullptr;
    case CSSPropertyID::TestMatchAllOrderedWithOptionalNoSingleItemOpt:
        // Skipped - Not computable
        return nullptr;
    case CSSPropertyID::TestMatchAllOrderedWithOptionalSingleItemOpt:
        // Skipped - Not computable
        return nullptr;
    case CSSPropertyID::TestMatchOne:
        // Skipped - Not computable
        return nullptr;
    case CSSPropertyID::TestMatchOneOrMoreAnyOrder:
        // Skipped - Not computable
        return nullptr;
    case CSSPropertyID::TestMatchOneOrMoreAnyOrderNoSingleItemOpt:
        // Skipped - Not computable
        return nullptr;
    case CSSPropertyID::TestMatchOneOrMoreAnyOrderWithCustomType:
        // Skipped - Not computable
        return nullptr;
    case CSSPropertyID::TestMatchOneOrMoreAnyOrderWithCustomTypeNoSingleItemOpt:
        // Skipped - Not computable
        return nullptr;
    case CSSPropertyID::TestMatchOneOrMoreAnyOrderWithPreserveOrder:
        // Skipped - Not computable
        return nullptr;
    case CSSPropertyID::TestMatchOneOrMoreAnyOrderWithPreserveOrderAndCustomType:
        // Skipped - Not computable
        return nullptr;
    case CSSPropertyID::TestMatchOneOrMoreAnyOrderWithPreserveOrderAndCustomTypeNoSingleItemOpt:
        // Skipped - Not computable
        return nullptr;
    case CSSPropertyID::TestMatchOneOrMoreAnyOrderWithPreserveOrderNoSingleItemOpt:
        // Skipped - Not computable
        return nullptr;
    case CSSPropertyID::TestMatchOneWithGroupWithSettingsFlag:
        // Skipped - Not computable
        return nullptr;
    case CSSPropertyID::TestMatchOneWithKeywordWithSettingsFlag:
        // Skipped - Not computable
        return nullptr;
    case CSSPropertyID::TestMatchOneWithMultipleKeywords:
        // Skipped - Not computable
        return nullptr;
    case CSSPropertyID::TestMatchOneWithReferenceWithSettingsFlag:
        // Skipped - Not computable
        return nullptr;
    case CSSPropertyID::TestMatchOneWithSettingsFlag:
        // Skipped - Not computable
        return nullptr;
    case CSSPropertyID::TestNumericValueRange:
        // Skipped - Not computable
        return nullptr;
    case CSSPropertyID::TestProperty:
        // Skipped - Not computable
        return nullptr;
    case CSSPropertyID::TestRenderStyleGetterNodeleteFalse:
        return ExtractorFunctions::extractTestRenderStyleGetterNodeleteFalse(extractorState);
    case CSSPropertyID::TestRenderStyleHasExplicitlySetPolicyAllAuthorOrigin:
        return ExtractorFunctions::extractTestRenderStyleHasExplicitlySetPolicyAllAuthorOrigin(extractorState);
    case CSSPropertyID::TestRenderStyleHasExplicitlySetPolicyAllBorderRadius:
        return ExtractorFunctions::extractTestRenderStyleHasExplicitlySetPolicyAllBorderRadius(extractorState);
    case CSSPropertyID::TestRenderStyleHasExplicitlySetPolicyValueOnly:
        return ExtractorFunctions::extractTestRenderStyleHasExplicitlySetPolicyValueOnly(extractorState);
    case CSSPropertyID::TestRenderStyleStorageOneLevelEnum:
        return ExtractorFunctions::extractTestRenderStyleStorageOneLevelEnum(extractorState);
    case CSSPropertyID::TestRenderStyleStorageOneLevelRaw:
        return ExtractorFunctions::extractTestRenderStyleStorageOneLevelRaw(extractorState);
    case CSSPropertyID::TestRenderStyleStorageOneLevelReference:
        return ExtractorFunctions::extractTestRenderStyleStorageOneLevelReference(extractorState);
    case CSSPropertyID::TestRenderStyleStorageOneLevelValue:
        return ExtractorFunctions::extractTestRenderStyleStorageOneLevelValue(extractorState);
    case CSSPropertyID::TestRenderStyleStorageTwoLevelEnum:
        return ExtractorFunctions::extractTestRenderStyleStorageTwoLevelEnum(extractorState);
    case CSSPropertyID::TestRenderStyleStorageTwoLevelRaw:
        return ExtractorFunctions::extractTestRenderStyleStorageTwoLevelRaw(extractorState);
    case CSSPropertyID::TestRenderStyleStorageTwoLevelReference:
        return ExtractorFunctions::extractTestRenderStyleStorageTwoLevelReference(extractorState);
    case CSSPropertyID::TestRenderStyleStorageTwoLevelValue:
        return ExtractorFunctions::extractTestRenderStyleStorageTwoLevelValue(extractorState);
    case CSSPropertyID::TestSettingsOne:
        return ExtractorFunctions::extractTestSettingsOne(extractorState);
    case CSSPropertyID::TestUnboundedRepetitionWithCommasWithMin:
        // Skipped - Not computable
        return nullptr;
    case CSSPropertyID::TestUnboundedRepetitionWithCommasWithMinNoSingleItemOpt:
        // Skipped - Not computable
        return nullptr;
    case CSSPropertyID::TestUnboundedRepetitionWithCommasWithMinSingleItemOpt:
        // Skipped - Not computable
        return nullptr;
    case CSSPropertyID::TestUnboundedRepetitionWithSpacesNoMin:
        // Skipped - Not computable
        return nullptr;
    case CSSPropertyID::TestUnboundedRepetitionWithSpacesNoMinNoSingleItemOpt:
        // Skipped - Not computable
        return nullptr;
    case CSSPropertyID::TestUnboundedRepetitionWithSpacesWithMin:
        // Skipped - Not computable
        return nullptr;
    case CSSPropertyID::TestUnboundedRepetitionWithSpacesWithMinNoSingleItemOpt:
        // Skipped - Not computable
        return nullptr;
    case CSSPropertyID::TestUnboundedRepetitionWithSpacesWithMinSingleItemOpt:
        // Skipped - Not computable
        return nullptr;
    case CSSPropertyID::TestUrlWithModifiers:
        // Skipped - Not computable
        return nullptr;
    case CSSPropertyID::TestUrlWithNoModifiers:
        // Skipped - Not computable
        return nullptr;
    case CSSPropertyID::TestUsingSharedRule:
        // Skipped - Not computable
        return nullptr;
    case CSSPropertyID::TestUsingSharedRuleExported:
        // Skipped - Not computable
        return nullptr;
    case CSSPropertyID::TestUsingSharedRuleWithOverrideFunction:
        // Skipped - Not computable
        return nullptr;
    case CSSPropertyID::TestSinkPriority:
        // Skipped - Not computable
        return nullptr;
    case CSSPropertyID::TestLogicalPropertyGroupPhysicalHorizontal:
        // Skipped - Not computable
        return nullptr;
    case CSSPropertyID::TestLogicalPropertyGroupPhysicalVertical:
        return ExtractorFunctions::extractTestLogicalPropertyGroupPhysicalVertical(extractorState);
    case CSSPropertyID::TestLogicalPropertyGroupLogicalBlock:
        // Logical properties are handled by recursing using the direction resolved property.
        return extractValue(extractorState, CSSProperty::resolveDirectionAwareProperty(id, extractorState.style.writingMode()));
    case CSSPropertyID::TestLogicalPropertyGroupLogicalInline:
        // Skipped - Not computable
        return nullptr;
    case CSSPropertyID::All:
        // Skipped - Not computable
        return nullptr;
    case CSSPropertyID::Font:
        // Skipped - Not computable
        return nullptr;
    case CSSPropertyID::TestShorthandOne:
        // Skipped - Not computable
        return nullptr;
    case CSSPropertyID::TestShorthandTwo:
        // Skipped - Not computable
        return nullptr;
    }
    ASSERT_NOT_REACHED();
    return nullptr;
}


void ExtractorGenerated::extractValueSerialization(ExtractorState& extractorState, StringBuilder& builder, const CSS::SerializationContext& context, CSSPropertyID id)
{
    switch (id) {
    case CSSPropertyID::Invalid:
        break;
    case CSSPropertyID::Custom:
        ASSERT_NOT_REACHED();
        break;
    case CSSPropertyID::TestTopPriority:
        // Skipped - Not computable
        return;
    case CSSPropertyID::TestHighPriority:
        // Skipped - Not computable
        return;
    case CSSPropertyID::TestMediumPriority:
        // Skipped - Not computable
        return;
    case CSSPropertyID::BackgroundCoordinatedValueListPropertyTestDiscrete:
        ExtractorFunctions::extractBackgroundCoordinatedValueListPropertyTestDiscreteSerialization(extractorState, builder, context);
        return;
    case CSSPropertyID::BackgroundCoordinatedValueListPropertyTestTwo:
        ExtractorFunctions::extractBackgroundCoordinatedValueListPropertyTestTwoSerialization(extractorState, builder, context);
        return;
    case CSSPropertyID::FirstTestDescriptorForFirstDescriptor:
        // Skipped - Descriptor-only property
        return;
    case CSSPropertyID::FirstTestDescriptorForSecondDescriptor:
        // Skipped - Descriptor-only property
        return;
    case CSSPropertyID::TestAnimationWrapper:
        ExtractorFunctions::extractTestAnimationWrapperSerialization(extractorState, builder, context);
        return;
    case CSSPropertyID::TestAnimationWrapperAccelerationAlways:
        ExtractorFunctions::extractTestAnimationWrapperAccelerationAlwaysSerialization(extractorState, builder, context);
        return;
    case CSSPropertyID::TestAnimationWrapperAccelerationThreadedOnly:
        ExtractorFunctions::extractTestAnimationWrapperAccelerationThreadedOnlySerialization(extractorState, builder, context);
        return;
    case CSSPropertyID::TestBoundedRepetitionWithCommas:
        // Skipped - Not computable
        return;
    case CSSPropertyID::TestBoundedRepetitionWithCommasFixed:
        // Skipped - Not computable
        return;
    case CSSPropertyID::TestBoundedRepetitionWithCommasNoSingleItemOpt:
        // Skipped - Not computable
        return;
    case CSSPropertyID::TestBoundedRepetitionWithCommasSingleItemOpt:
        // Skipped - Not computable
        return;
    case CSSPropertyID::TestBoundedRepetitionWithSpaces:
        // Skipped - Not computable
        return;
    case CSSPropertyID::TestBoundedRepetitionWithSpacesFixed:
        // Skipped - Not computable
        return;
    case CSSPropertyID::TestBoundedRepetitionWithSpacesNoSingleItemOpt:
        // Skipped - Not computable
        return;
    case CSSPropertyID::TestBoundedRepetitionWithSpacesSingleItemOpt:
        // Skipped - Not computable
        return;
    case CSSPropertyID::TestBoundedRepetitionWithSpacesWithType:
        // Skipped - Not computable
        return;
    case CSSPropertyID::TestBoundedRepetitionWithSpacesWithTypeNoSingleItemOpt:
        // Skipped - Not computable
        return;
    case CSSPropertyID::TestBoundedRepetitionWithSpacesWithTypeWithDefaultPrevious:
        // Skipped - Not computable
        return;
    case CSSPropertyID::TestBoundedRepetitionWithSpacesWithTypeWithDefaultPreviousTwo:
        // Skipped - Not computable
        return;
    case CSSPropertyID::TestColor:
        ExtractorFunctions::extractTestColorSerialization(extractorState, builder, context);
        return;
    case CSSPropertyID::TestColorAllowsTypesAbsolute:
        ExtractorFunctions::extractTestColorAllowsTypesAbsoluteSerialization(extractorState, builder, context);
        return;
    case CSSPropertyID::TestColorPropertyWithVisitedLinkSupport:
        ExtractorFunctions::extractTestColorPropertyWithVisitedLinkSupportSerialization(extractorState, builder, context);
        return;
    case CSSPropertyID::TestCustomExtractor:
        ExtractorCustom::extractTestCustomExtractorSerialization(extractorState, builder, context);
        return;
    case CSSPropertyID::TestFunctionBoundedParameters:
        // Skipped - Not computable
        return;
    case CSSPropertyID::TestFunctionFixedParameters:
        // Skipped - Not computable
        return;
    case CSSPropertyID::TestFunctionNoParameters:
        // Skipped - Not computable
        return;
    case CSSPropertyID::TestFunctionParametersMatchAllAnyOrder:
        // Skipped - Not computable
        return;
    case CSSPropertyID::TestFunctionParametersMatchAllAnyOrderWithOptional:
        // Skipped - Not computable
        return;
    case CSSPropertyID::TestFunctionParametersMatchAllOrdered:
        // Skipped - Not computable
        return;
    case CSSPropertyID::TestFunctionParametersMatchAllOrderedWithOptional:
        // Skipped - Not computable
        return;
    case CSSPropertyID::TestFunctionParametersMatchOneOrMoreAnyOrder:
        // Skipped - Not computable
        return;
    case CSSPropertyID::TestFunctionSingleParameter:
        // Skipped - Not computable
        return;
    case CSSPropertyID::TestFunctionSingleParameterMatchOne:
        // Skipped - Not computable
        return;
    case CSSPropertyID::TestFunctionSingleParameterOptional:
        // Skipped - Not computable
        return;
    case CSSPropertyID::TestFunctionUnboundedParametersNoMin:
        // Skipped - Not computable
        return;
    case CSSPropertyID::TestFunctionUnboundedParametersWithMinimum:
        // Skipped - Not computable
        return;
    case CSSPropertyID::TestImage:
        // Skipped - Not computable
        return;
    case CSSPropertyID::TestImageNoImageSet:
        // Skipped - Not computable
        return;
    case CSSPropertyID::TestKeyword:
        // Skipped - Not computable
        return;
    case CSSPropertyID::TestKeywordWithAliasedTo:
        // Skipped - Not computable
        return;
    case CSSPropertyID::TestMatchAllAnyOrder:
        // Skipped - Not computable
        return;
    case CSSPropertyID::TestMatchAllAnyOrderWithCustomType:
        // Skipped - Not computable
        return;
    case CSSPropertyID::TestMatchAllAnyOrderWithOptional:
        // Skipped - Not computable
        return;
    case CSSPropertyID::TestMatchAllAnyOrderWithOptionalAndCustomType:
        // Skipped - Not computable
        return;
    case CSSPropertyID::TestMatchAllAnyOrderWithOptionalAndMultipleRequiredAndCustomType:
        // Skipped - Not computable
        return;
    case CSSPropertyID::TestMatchAllAnyOrderWithOptionalAndMultipleRequiredAndCustomTypeNoSingleItemOpt:
        // Skipped - Not computable
        return;
    case CSSPropertyID::TestMatchAllAnyOrderWithOptionalAndMultipleRequiredAndPreserveOrderAndCustomType:
        // Skipped - Not computable
        return;
    case CSSPropertyID::TestMatchAllAnyOrderWithOptionalAndMultipleRequiredAndPreserveOrderAndCustomTypeNoSingleItemOpt:
        // Skipped - Not computable
        return;
    case CSSPropertyID::TestMatchAllAnyOrderWithOptionalAndPreserveOrderAndCustomType:
        // Skipped - Not computable
        return;
    case CSSPropertyID::TestMatchAllAnyOrderWithOptionalNoSingleItemOpt:
        // Skipped - Not computable
        return;
    case CSSPropertyID::TestMatchAllAnyOrderWithOptionalSingleItemOpt:
        // Skipped - Not computable
        return;
    case CSSPropertyID::TestMatchAllAnyOrderWithOptionalWithPreserveOrder:
        // Skipped - Not computable
        return;
    case CSSPropertyID::TestMatchAllAnyOrderWithOptionalWithPreserveOrderNoSingleItemOpt:
        // Skipped - Not computable
        return;
    case CSSPropertyID::TestMatchAllAnyOrderWithPreserveOrder:
        // Skipped - Not computable
        return;
    case CSSPropertyID::TestMatchAllAnyOrderWithPreserveOrderAndCustomType:
        // Skipped - Not computable
        return;
    case CSSPropertyID::TestMatchAllAnyOrderWithPreserveOrderNoSingleItemOpt:
        // Skipped - Not computable
        return;
    case CSSPropertyID::TestMatchAllOrdered:
        // Skipped - Not computable
        return;
    case CSSPropertyID::TestMatchAllOrderedWithCustomType:
        // Skipped - Not computable
        return;
    case CSSPropertyID::TestMatchAllOrderedWithOptional:
        // Skipped - Not computable
        return;
    case CSSPropertyID::TestMatchAllOrderedWithOptionalAndCustomType:
        // Skipped - Not computable
        return;
    case CSSPropertyID::TestMatchAllOrderedWithOptionalAndCustomTypeAndNoSingleItemOpt:
        // Skipped - Not computable
        return;
    case CSSPropertyID::TestMatchAllOrderedWithOptionalAndMultipleRequired:
        // Skipped - Not computable
        return;
    case CSSPropertyID::TestMatchAllOrderedWithOptionalAndMultipleRequiredAndCustomType:
        // Skipped - Not computable
        return;
    case CSSPropertyID::TestMatchAllOrderedWithOptionalNoSingleItemOpt:
        // Skipped - Not computable
        return;
    case CSSPropertyID::TestMatchAllOrderedWithOptionalSingleItemOpt:
        // Skipped - Not computable
        return;
    case CSSPropertyID::TestMatchOne:
        // Skipped - Not computable
        return;
    case CSSPropertyID::TestMatchOneOrMoreAnyOrder:
        // Skipped - Not computable
        return;
    case CSSPropertyID::TestMatchOneOrMoreAnyOrderNoSingleItemOpt:
        // Skipped - Not computable
        return;
    case CSSPropertyID::TestMatchOneOrMoreAnyOrderWithCustomType:
        // Skipped - Not computable
        return;
    case CSSPropertyID::TestMatchOneOrMoreAnyOrderWithCustomTypeNoSingleItemOpt:
        // Skipped - Not computable
        return;
    case CSSPropertyID::TestMatchOneOrMoreAnyOrderWithPreserveOrder:
        // Skipped - Not computable
        return;
    case CSSPropertyID::TestMatchOneOrMoreAnyOrderWithPreserveOrderAndCustomType:
        // Skipped - Not computable
        return;
    case CSSPropertyID::TestMatchOneOrMoreAnyOrderWithPreserveOrderAndCustomTypeNoSingleItemOpt:
        // Skipped - Not computable
        return;
    case CSSPropertyID::TestMatchOneOrMoreAnyOrderWithPreserveOrderNoSingleItemOpt:
        // Skipped - Not computable
        return;
    case CSSPropertyID::TestMatchOneWithGroupWithSettingsFlag:
        // Skipped - Not computable
        return;
    case CSSPropertyID::TestMatchOneWithKeywordWithSettingsFlag:
        // Skipped - Not computable
        return;
    case CSSPropertyID::TestMatchOneWithMultipleKeywords:
        // Skipped - Not computable
        return;
    case CSSPropertyID::TestMatchOneWithReferenceWithSettingsFlag:
        // Skipped - Not computable
        return;
    case CSSPropertyID::TestMatchOneWithSettingsFlag:
        // Skipped - Not computable
        return;
    case CSSPropertyID::TestNumericValueRange:
        // Skipped - Not computable
        return;
    case CSSPropertyID::TestProperty:
        // Skipped - Not computable
        return;
    case CSSPropertyID::TestRenderStyleGetterNodeleteFalse:
        ExtractorFunctions::extractTestRenderStyleGetterNodeleteFalseSerialization(extractorState, builder, context);
        return;
    case CSSPropertyID::TestRenderStyleHasExplicitlySetPolicyAllAuthorOrigin:
        ExtractorFunctions::extractTestRenderStyleHasExplicitlySetPolicyAllAuthorOriginSerialization(extractorState, builder, context);
        return;
    case CSSPropertyID::TestRenderStyleHasExplicitlySetPolicyAllBorderRadius:
        ExtractorFunctions::extractTestRenderStyleHasExplicitlySetPolicyAllBorderRadiusSerialization(extractorState, builder, context);
        return;
    case CSSPropertyID::TestRenderStyleHasExplicitlySetPolicyValueOnly:
        ExtractorFunctions::extractTestRenderStyleHasExplicitlySetPolicyValueOnlySerialization(extractorState, builder, context);
        return;
    case CSSPropertyID::TestRenderStyleStorageOneLevelEnum:
        ExtractorFunctions::extractTestRenderStyleStorageOneLevelEnumSerialization(extractorState, builder, context);
        return;
    case CSSPropertyID::TestRenderStyleStorageOneLevelRaw:
        ExtractorFunctions::extractTestRenderStyleStorageOneLevelRawSerialization(extractorState, builder, context);
        return;
    case CSSPropertyID::TestRenderStyleStorageOneLevelReference:
        ExtractorFunctions::extractTestRenderStyleStorageOneLevelReferenceSerialization(extractorState, builder, context);
        return;
    case CSSPropertyID::TestRenderStyleStorageOneLevelValue:
        ExtractorFunctions::extractTestRenderStyleStorageOneLevelValueSerialization(extractorState, builder, context);
        return;
    case CSSPropertyID::TestRenderStyleStorageTwoLevelEnum:
        ExtractorFunctions::extractTestRenderStyleStorageTwoLevelEnumSerialization(extractorState, builder, context);
        return;
    case CSSPropertyID::TestRenderStyleStorageTwoLevelRaw:
        ExtractorFunctions::extractTestRenderStyleStorageTwoLevelRawSerialization(extractorState, builder, context);
        return;
    case CSSPropertyID::TestRenderStyleStorageTwoLevelReference:
        ExtractorFunctions::extractTestRenderStyleStorageTwoLevelReferenceSerialization(extractorState, builder, context);
        return;
    case CSSPropertyID::TestRenderStyleStorageTwoLevelValue:
        ExtractorFunctions::extractTestRenderStyleStorageTwoLevelValueSerialization(extractorState, builder, context);
        return;
    case CSSPropertyID::TestSettingsOne:
        ExtractorFunctions::extractTestSettingsOneSerialization(extractorState, builder, context);
        return;
    case CSSPropertyID::TestUnboundedRepetitionWithCommasWithMin:
        // Skipped - Not computable
        return;
    case CSSPropertyID::TestUnboundedRepetitionWithCommasWithMinNoSingleItemOpt:
        // Skipped - Not computable
        return;
    case CSSPropertyID::TestUnboundedRepetitionWithCommasWithMinSingleItemOpt:
        // Skipped - Not computable
        return;
    case CSSPropertyID::TestUnboundedRepetitionWithSpacesNoMin:
        // Skipped - Not computable
        return;
    case CSSPropertyID::TestUnboundedRepetitionWithSpacesNoMinNoSingleItemOpt:
        // Skipped - Not computable
        return;
    case CSSPropertyID::TestUnboundedRepetitionWithSpacesWithMin:
        // Skipped - Not computable
        return;
    case CSSPropertyID::TestUnboundedRepetitionWithSpacesWithMinNoSingleItemOpt:
        // Skipped - Not computable
        return;
    case CSSPropertyID::TestUnboundedRepetitionWithSpacesWithMinSingleItemOpt:
        // Skipped - Not computable
        return;
    case CSSPropertyID::TestUrlWithModifiers:
        // Skipped - Not computable
        return;
    case CSSPropertyID::TestUrlWithNoModifiers:
        // Skipped - Not computable
        return;
    case CSSPropertyID::TestUsingSharedRule:
        // Skipped - Not computable
        return;
    case CSSPropertyID::TestUsingSharedRuleExported:
        // Skipped - Not computable
        return;
    case CSSPropertyID::TestUsingSharedRuleWithOverrideFunction:
        // Skipped - Not computable
        return;
    case CSSPropertyID::TestSinkPriority:
        // Skipped - Not computable
        return;
    case CSSPropertyID::TestLogicalPropertyGroupPhysicalHorizontal:
        // Skipped - Not computable
        return;
    case CSSPropertyID::TestLogicalPropertyGroupPhysicalVertical:
        ExtractorFunctions::extractTestLogicalPropertyGroupPhysicalVerticalSerialization(extractorState, builder, context);
        return;
    case CSSPropertyID::TestLogicalPropertyGroupLogicalBlock:
        // Logical properties are handled by recursing using the direction resolved property.
        extractValueSerialization(extractorState, builder, context, CSSProperty::resolveDirectionAwareProperty(id, extractorState.style.writingMode()));
        return;
    case CSSPropertyID::TestLogicalPropertyGroupLogicalInline:
        // Skipped - Not computable
        return;
    case CSSPropertyID::All:
        // Skipped - Not computable
        return;
    case CSSPropertyID::Font:
        // Skipped - Not computable
        return;
    case CSSPropertyID::TestShorthandOne:
        // Skipped - Not computable
        return;
    case CSSPropertyID::TestShorthandTwo:
        // Skipped - Not computable
        return;
    }
    ASSERT_NOT_REACHED();
}

} // namespace WebCore
} // namespace Style

