// This file is automatically generated from CSSProperties.json by the process-css-properties.py script. Do not edit it.

#pragma once

#include <WebCore/LayoutUnit.h>
#include <WebCore/RenderElement.h>
#include <WebCore/StyleComputedStyle.h>
#include <WebCore/UsedStyleReferenceSize.h>
#include <optional>
#include <wtf/CheckedRef.h>

namespace WebCore {

class UsedStyleProperties {
public:
    const Style::ComputedStyle& computedStyle() const LIFETIME_BOUND { return m_renderer->style(); }

protected:
    explicit UsedStyleProperties(const RenderElement& renderer LIFETIME_BOUND)
        : m_renderer(renderer)
    {
    }

    // Resolves the reference a percentage value evaluates against (e.g. the containing
    // block inline size). Renderer-derived, so hand-written out-of-line in UsedStyle.cpp.
    LayoutUnit resolveReferenceSize(ReferenceSize) const;

    // const: a UsedStyle view never rebinds its renderer, so it can be read without a stack-local guard.
    const CheckedRef<const RenderElement> m_renderer;
};

} // namespace WebCore

